### ISSUE TITLE
Support `verify` as an extension

### ISSUE THREAD

**Issue by jherico** [michel-kraemer/gradle-download-task#102]
I currently work on a project with a number of upstream library dependencies stored on S3 in tgz files.

I use the following variables and code to download them....

```
def packages = [
    qt: [ file: qtFile, sharedLibFolder: '', includeLibs: ['lib/*.so', 'plugins/*/*.so'] ],
    bullet: [ file: 'bullet-2.83_armv8-libcpp.tgz' ],
    draco: [ file: 'draco_armv8-libcpp.tgz' ],
    gvr: [ file: 'gvrsdk_v1.101.0.tgz' ],
    openssl: [ file: 'openssl-1.1.0g_armv8.tgz'],
    polyvox: [ file: 'polyvox_armv8-libcpp.tgz', sharedLibFolder: 'lib', includeLibs: ['Release/libPolyVoxCore.so', 'libPolyVoxUtil.so'] ],
    tbb: [ file: 'tbb-2018_U1_armv8_libcpp.tgz', sharedLibFolder: 'lib/release', includeLibs: ['libtbb.so', 'libtbbmalloc.so'] ]
]

task downloadDependencies {
    doLast {
        packages.each { entry ->
            def filename = entry.value['file'];
            def url = baseUrl + filename;
            download {
                src url
                dest new File(baseFolder, filename)
                onlyIfNewer true
            } 
        }
    }
}
```

I would _like_ to be able to add verification as well, based on known MD5 values.  But only the `download` command has been exposed in the groovy language.  What's preventing the exposure of the verify action as an extension as well?

**Comment by jherico** [comment]
An alternative would be to integrate the `verify` arguments as optional arguments to the `download` task / extension.

**Comment by michel-kraemer** [comment]
Thanks for the idea! I just added the extension. I called it `verifyChecksum` in order to reduce the possibility of naming collisions with existing plugins. The feature will be in the next version.
