### ISSUE TITLE
Support unpacking archives in the download task

### ISSUE THREAD

**Issue by jherico** [michel-kraemer/gradle-download-task#103]
I'd love to be able to download an archive and extract it as a single task or groovy command, like so

    download {
        src url
        dest new File(baseFolder, filename)
        extractTo new File(baseFolder, folderName)
        onlyIfNewer true
    }

where if you download a zip or a tgz file you can have the download command extract the archive to the specified folder

This would be equivalent to the above `download` followed by 

    copy {
        from tarTree(resources.gzip(new File(baseFolder, filename)))
        into new File(baseFolder, folderName)
    }

**Comment by michel-kraemer** [comment]
Pretty good idea, but I think this should already be possible with existing means. Have a look at the following example:
https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/unzip.gradle

Adding such a feature to gradle-download-task seems to me like reinventing the wheel. The copy task combined with `zipTree` or `tarTree` is very flexible and well tested. The only clean and maintainable solution IMHO would be to somehow auto-magically add a copy task succeeding the download task if `extractTo` is set. I'm not sure if this is possible in Gradle, but pull requests are very welcome! :smile:

**Comment by jherico** [comment]
My main issue with the unzip example is that because it's a distinct task, there's no way to short-circuit it if the file has already been downloaded and unzipped.  The the onlyIfNewer flag, I can skip the downloads, but I haven't seen anything that will let me skip the archive extraction if the target folder has already been created.  With a large set of dependencies, it's a pain to have extract run every time i do a build.

**Comment by michel-kraemer** [comment]
I just tried to reproduce what you are saying. I added `overwrite false` and `onlyIfNewer true` to the `Download` task and ran the example twice.

The first time it downloads the file as expected:

```
$ gradle -b unzip.gradle
Download https://github.com/michel-kraemer/gradle-download-task/archive/1.0.zip

> Task :downloadZipFile
Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Thu, 04 Mar 2038 07:28:21 -0000; secure; HttpOnly". Invalid 'expires' attribute: Thu, 04 Mar 2038 07:28:21 -0000


BUILD SUCCESSFUL in 1s
2 actionable tasks: 2 executed
```

The second time it says that everything is up-to-date:

```
$ gradle -b unzip.gradle

BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 up-to-date
```

Isn't this what you expect?

**Comment by jherico** [comment]
If the file on the server side changes, it will re-download, but will the `overwrite false` prevent it from unzipping the new file?  

My goal is to be able to download and decompress a bunch of pre-requisites for the build process such that if I've already downloaded the content, the tasks produce minimal overhead, but if the server side content changes, the new content is downloaded, replaces the old content, and on subsequent runs I get minimal overhead again, until such time as another server side file changes.

**Comment by jherico** [comment]
I'll take a look at the behavior when I'm back at work next week.  Thanks for the effort.
