### ISSUE TITLE
[SUGGESTION] Support configuration for multiple destinations

### ISSUE THREAD

**Issue by SammyJumpstart23** [michel-kraemer/gradle-download-task#104]
I have an issue where two wsdls I'm trying to download have methods with the same signature. Given the current state of the plugin, it's only possible to set one directory as dest.

I'm aware that my problem can be solved by writing multiple download tasks with different destinations each, but I don't want to clutter up my build if possible.

So as such, is it possible to have configuration for multiple destinations? Or maybe I missed something in the docs that can help with my problem. Any advice is greatly appreciated.

**Comment by michel-kraemer** [comment]
Maybe you can make use of the possibility to set a Closure as dest:

```gradle
dest {
  if (whatever_your_destination_depends_on) {
    return dest1
  }
  return dest2
}
```

This is demonstrated in the following example:

https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/srcAndDestClosure.gradle

If this does not help, could you please provide some more details on what you want to achieve (maybe with sample code)?

**Comment by michel-kraemer** [comment]
I'm closing this issue due to lack of feedback. Feel free to reopen it if you have further questions.
