### ISSUE TITLE
Retained ETags record silently skips download

### ISSUE THREAD

**Issue by liblit** [michel-kraemer/gradle-download-task#107]
Using Gradle 4.6 and gradle-download-task 3.4.0, the following `build.gradle` tries to use ETags to avoid downloading when the desired resource has not changed:

``` gradle
plugins {
  id 'de.undercouch.download' version '3.4.0'
}

task downloadJLex(type: Download) {
  src 'http://www.cs.princeton.edu/~appel/modern/java/JLex/current/Main.java'
  dest '.'
  onlyIfModified true
  useETag true
}
```

Now try the following three builds, in order:

1. Start with a clean tree: no existing `build` subdirectory and no `Main.java` file. Run the `downloadJLex` task, such as via `./gradlew downloadJLex`. This behaves as expected: Gradle downloads the resource and saves it as `Main.java`, records the resource's ETag in `build/download-task/etags.json`, and completes without error.

1. Now delete `Main.java`, but leave `build/download-task/etags.json` alone. Run the `downloadJLex` task again. The Gradle completes without error, but creates no `Main.java` file.

1. Now delete `build/download-task/etags.json`. Run the `downloadJLex` task again. This behaves correctly: Gradle downloads the resource and saves it as `Main.java`, records the resource's ETag in `build/download-task/etags.json`, and completes without error.

Something in step 2 is behaving rather strangely, and in my opinion incorrectly. I can see the logic behind skipping the dowload if the ETag is unchanged, but surely that should only come into play if the output file is already present. If the desired output file is missing entirely, then should either be copied from some local cache or downloaded anew, regardless of any ETags. Perhaps the ideal behavior would be to copy the file from a local cache if this cached file's ETag matches what the server says it would provide, or to download a fresh copy if the cached copy's ETag no longer matches the server. I don't understand Gradle caching well enough to know whether that's feasible, but using the ETag value as a cache key or validity check seems like the right idea.

For your testing convenience, here is a shell script that automates the three builds described above:

``` sh

target=Main.java

build() {
  ./gradlew downloadJLex
  if [ -f $target ]; then
    echo "*** $target exists"
  else
    echo "*** $target is missing"
  fi
}

rm -rf build $target
build

rm -rf $target
build

rm build/download-task/etags.json
build
```

This script prints `*** Main.java exists` after the first build, then `*** Main.java is missing` after the second build, then `*** Main.java exists` after the third build. I claim that the second build should behave differently: it should create `Main.java` and therefore print `*** Main.java exists` like the others.

**Comment by michel-kraemer** [comment]
You're right. This is a bug. I will fix it as soon as possible.

**Comment by liblit** [comment]
Looks good to me. Thank you for the [speedy fix](https://github.com/michel-kraemer/gradle-download-task/commit/0e9f638aca09cb84e5a91268a3926cd972dac315) and [new release](https://github.com/michel-kraemer/gradle-download-task/releases/tag/3.4.1)!
