### ISSUE TITLE
Help wanted to implement combined download+verify task

### ISSUE THREAD

**Issue by liblit** [michel-kraemer/gradle-download-task#108]
Using Gradle 4.6 and gradle-download-task 3.4.0, the vast majority of my downloads have the same general pattern: download a given URL to a given file, then verify that download using a given checksum. I would like to refactor this recurring pattern into a custom task, but I don‘t know how. This is really more of a support question than a bug report, but I hope that you will lend me some wisdom so that I can use gradle-download-task more awesomely.

The following is a representative example of a typical download task:

``` gradle
task downloadJLex {
  outputs.file 'src/JLex/Main.java'  // varies
  doLast {
    download {
      src 'http://www.cs.princeton.edu/~appel/modern/java/JLex/current/Main.java'  // varies
      dest outputs.files.singleFile
      overwrite true
    }
    verifyChecksum {
      src outputs.files.singleFile
      checksum 'fe0cff5db3e2f0f5d67a153cf6c783af'  // varies
    }
  }
}
```

Other than the task name, three `  // varies` comments above mark the only parts of this pattern vary throughout my project:

1. The output file into which the URL should be saved.
1. The URL to download.
1. The checksum used to verify the download.

My partial, non-working effort to create a custom class consists of the following Gradle code added directly to a subproject's `build.gradle`:

``` gradle
class VerifiedDownload extends org.gradle.api.DefaultTask {

  @Input String src
  @Input String checksum
  @OutputFile File dest

  @TaskAction
  downloadAndVerify() {
    download {
      src this.src
      dest this.dest
      overwrite true
      onlyIfModified true
    }
    verifyChecksum {
      src this.dest
      checksum this.checksum
    }
  }
}
```

Unfortunately, my use of `download` and `verifyChecksum` is wrong. If I try to instantiate my custom task...

``` gradle
task downloadJLex(type: VerifiedDownload) {
  src 'http://www.cs.princeton.edu/~appel/modern/java/JLex/current/Main.java'
  checksum 'fe0cff5db3e2f0f5d67a153cf6c783af'
  dest file('src/JLex/Main.java')
}
```

... then Gradle fails, reporting  `Could not find method download() for arguments [VerifiedDownload$_downloadAndVerify_closure1@49958194] on task ':com.ibm.wala.cast.java.test.data:downloadJLex' of type VerifiedDownload.`

I suspect that my use of `this.src`, `this.dest`, and `this.checksum` in the `VerifiedDownload` constructor may be bogus as well. I am not sure how to access these fields of the current `VerifiedDownload` task instance versus invoking the `src`, `dest`, and `checksum` methods that would be available inside the `download` and `verifyChecksum` if I were using those blocks correctly.

I hope that my *intention* is clear from the above examples. I would be grateful for any hints as to the right way to turn that intention into working code.

**Comment by michel-kraemer** [comment]
Please try `project.download` and `project.verifyChecksum` instead of `download` and `verifyChecksum`.

**Comment by liblit** [comment]
`project.download` and `project.verifyChecksum` worked perfectly. Thank you, @michel-kraemer!
