### ISSUE TITLE
Feature request: download checksum file for requested file

### ISSUE THREAD

**Issue by UltimateGeek** [michel-kraemer/gradle-download-task#109]
Artifact repositories like Artifactory provide checksum files for all hosted artifacts. For example:

    artifact.zip
    artifact.zip.md5
    artifact.zip.sha1

I can write a task based on this gradle plugin to automatically download the md5 file, and use it to verify. 

I contend this is a common pattern for which this extension could support by design:

    task downloadArtifact(type: DownloadAndVerify) {
        src 'http://www.example.com/artifact.zip'
        checksum_src 'http://www.example.com/artifact.zip.md5'
        dest buildDir
    }

If you agree, I can help develop the code in here to do this.

If you disagree, then I might write gradle script code to do it, possibly creating another gradle plugin that uses yours as a dependency.

Also for consideration is that a lot of artifact repos have PGP signature files provided instead of checksums. So another example of this pattern is:

    task get_binutils(type: DownloadAndVerify) {
        def pkg = "http://mirrors.kernel.org/archlinux/core/os/x86_64/binutils-2.29.1-2-x86_64.pkg.tar.xz"
        src pkg
        pgp_signature_src "${pkg}.sig"
        dest buildDir
    }

Perhaps verifying against a PGP signature is outside of the scope of this project, but since verifying a checksum is, I was thinking you'd consider at least the download-checksum-and-use-it proposal.

**Comment by michel-kraemer** [comment]
Thanks a lot for your offer to help. I really appreciate that.

Your idea reminded me of an earlier pull request (#54). The main problem we had there was that the file format for these checksum files is not standardised so every server can basically use its own format. If you could solve this problem, it would be great.

Apart from that, I don't think mixing the `Download` task and the `Verify` task is a good idea. We should instead extend the `Verify` task to first support reading checksums from files and then download them from a URL. What do you think?

**Comment by UltimateGeek** [comment]
I don't understand why providing another class that combines the functionality of the Download and Verify classes together is a bad idea. Can you explain why?

The reason why I think it would useful to verify the checksum as part of the same task as the download is when one wants to enact this policy:

   * Bad data should be deleted when it does not match its checksum

Within the context of Gradle tracking outputs of tasks to determine if they are up-to-date, the Download task should rerun upon the next invocation of gradle if the previously downloaded file was bad. Although this could be accomplished by first verifying the checksum on the subsequent invocation, I contend it would be better for the original run of the task to fail:

   * Consider the completion state of a task as having failed when the data it produced was bad

The [verifyExtension.gradle](https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/verifyExtension.gradle) example has just one task defined, which is a step towards what I'm looking for (avoiding having a Download task in the build script that should not be depended on by anything except a Verify task). But it does not satisfy my desired state of deleting the file if it is bad at the end of the task. 

We could write another single-gradle-task example to accomplish what I'm suggesting, but it's going to be more complicated, and as such should probably have a unit or integration test. Furthermore, providing such an example would encourage the implementation to be copied over & over again throughout other projects. 

I'm proposing we have a solution that either provides a DSL to combine the Download and Verify classes' functionality, or add a DownloadAndVerify class (and avoid defining a DSL).

**Comment by UltimateGeek** [comment]
Regarding the problem of variation in the format of a checksum or signature file, I suggest the initial implementation not take on that problem, but instead write the code to:

* Assume the entire content in the file is the checksum or signature

When needed, a solution for accommodating other formats could be to allow a closure to be provided for processing the contents of the file.

**Comment by michel-kraemer** [comment]
Following up on your idea, I understand what you mean when you say you want to combine the functionality of `Download` and `Verify` but IMHO we shouldn't make the plugin too complicated. We already have a ton of options and parameters and I don't want to overwhelm the user with a too complicated API. Note that I'm not against this feature request in particular but against a general over-complication.

So, instead of extending the plugin I'd rather have a look at the example script that you mentioned first. I'd like to weigh off the effort of copy-and-pasting the sample script vs. extending the API. I hope you understand that and sorry for the inconvenience.

**Comment by UltimateGeek** [comment]
By "copy-paste", do you mean adding DSL to minimizing the code?

Here's how I achieve the functionality with the md5 checksum contained in the script. artifactory_* properties are in the user's init.gradle.

We could define a DownloadAndVerify task in groovy that automatically defines the doLast block.

```
def artifact_dir = "$buildDir/tarballs/"
def binary_package = "filename.zip"
def binary_package_md5 = "97c9170861e7aec25aa6f4114202ec89"
task download(type: Download) {
    def downloaded_file = new File(artifact_dir, binary_package)

    src "$artifactory_server/$binary_package"
    dest downloaded_file
    username artifactory_username
    password artifactory_password
    compress false
    onlyIfModified true
    useETag "all"
    timeout 20000 //20sec

    doLast {
        try {
            verifyChecksum {
                src downloaded_file
                algorithm 'MD5'
                checksum binary_package_md5
            }
        } catch (all) {
            downloaded_file.delete()
            throw all
        }
    }
}
```

Additional aspects to consider to minimize the amount of code to write each time:
* default values for `onlyIfModified` and `useETag`: without being `true` and `"all"`, the task always downloads. The desire is for there to be a common task that is used to download generic dependencies. These must always be changed for that.
* timeout should be 30 sec by default to match gradle's connection behvior. See [Increase default HTTP timeout to 30s #3268](https://github.com/gradle/gradle/pull/3268/commits/19de696b85dc4815c2b948d3432bce58590709bb)

**Comment by rendel** [comment]
One simple solution would be to allow to pass a closure to the checksum() method for lazy evaluation. One could then create a download task for the file, a download task for the checksum, then a verify task by reading the content of the downloaded checksum file.
At the moment, this is not possible and one cannot use the verify task if the checksum is not already available as a string.

**Comment by michel-kraemer** [comment]
@UltimateGeek Thanks for your sample script. AFAICT it only has about 6 lines more than if we'd put everything into one task. I don't know if this is really worth it. I'd like to hear opinions from other people first.

Regarding the default values for `onlyIfModified` or `timeout`. That's a pretty good idea. I'm currently thinking about a version 4.0 where we could introduce such changes. I'll keep that in mind.
