### ISSUE TITLE
Can't run a download task twice: AssertionError

### ISSUE THREAD

**Issue by topo75** [michel-kraemer/gradle-download-task#114]
When enabling assertions in the JVM, e.g. with gradle property: 
> org.gradle.jvmargs=-ea

then I'll get an AssertionError, if a download task is run a second time.

> &ast; Exception is:
> java.lang.AssertionError
>         at org.gradle.api.internal.tasks.TaskStateInternal.setOutcome(TaskStateInternal.java:52)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:81)
>         at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
>         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
>         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
> ...

**Comment by michel-kraemer** [comment]
Can you provide a small build file demonstrating the problem?

**Comment by topo75** [comment]
Here is a small build.gradle:

`task downloadLicense(type: Download) {`
`  src 'https://raw.githubusercontent.com/michel-kraemer/gradle-download-task/master/LICENSE.txt'`
`  dest buildDir`
`  onlyIfModified true`
`  overwrite false`
`}`

If you start it twice with
`gradlew downloadLicense --stacktrace -Dorg.gradle.jvmargs=-ea`
you'll get the stacktrace.

**Comment by michel-kraemer** [comment]
Thanks a lot!
