### ISSUE TITLE
Inconsistent failure due to javax.net.ssl.SSLException 

### ISSUE THREAD

**Issue by seanabraham** [michel-kraemer/gradle-download-task#117]
The download task generally works great for me, but I occasionally get a failure that looks like this:

```
* What went wrong:
Execution failed for task ':downloadSwiftCompiler'.
> javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

I've looked into this a bit but am a bit stuck because most sources point to a legitimate configuration issue but I only see this issue every now and again, it's not consistent. One other useful data point is that I have two download tasks that run in parallel, could they negatively interact with each other some how?

**Comment by michel-kraemer** [comment]
> One other useful data point is that I have two download tasks that run in parallel, could they negatively interact with each other some how?

Well, everything is possible, but the classes in gradle-download-task don't have static fields or anything else that could potentially cause problems in a multi-threaded scenario.

This is going to be very hard to debug. Are you able to provide a reproducer (a small example demonstrating the problem)?

**Comment by seanabraham** [comment]
Sorry, I haven't been able to create a reliable repro. I did notice a similar problem in Gradle recently and it looks like a fix was put up here:

https://github.com/gradle/gradle/pull/6721

Maybe we could try to obtain the SSLContext here similarly? I'm not very familiar with how this all works though.
