### ISSUE TITLE
Using more exact units

### ISSUE THREAD

**Issue by michaelzangl** [michel-kraemer/gradle-download-task#118]
The file size is currently divided by 1024, although it is displayed as KB, MB, GB.

The correct units to indicate that difference would be:
* KiB
* MiB
* GiB

**Comment by michel-kraemer** [comment]
Yes, this is actually correct, but gradle-download-task uses the same calculations and units as Gradle itself. Look at Gradle's resource operation that displays the progress when you're downloading an artefact:

https://github.com/gradle/gradle/blob/c9ce320/subprojects/dependency-management/src/main/java/org/gradle/internal/resource/transfer/ResourceOperation.java#L46-L57

Although I know the numbers aren't scientifically correct, I prefer to be consistent with Gradle here. Sorry.
