### ISSUE TITLE
How to disable output on CI server

### ISSUE THREAD

**Issue by avdv** [michel-kraemer/gradle-download-task#119]
Is it possible to disable the verbose output using environment variables or system properties?

**Comment by michel-kraemer** [comment]
What verbose output do you mean? gradle-download-task should only print the download progress.

By the way, there is a `quiet` parameter. Maybe this is already what you're looking for.

**Comment by avdv** [comment]
Yes, I don't want the download progress. It just messes up the build log.

How do I use the `quiet` parameter *without* changing any gradle file? Ie. can I set it using a command line parameter / env variable / system property?

**Comment by avdv** [comment]
```
Job's log exceeded limit of 4194304 bytes.
```

Or, in general, how about only enabling the progress when stdout is connected to a terminal?

**Comment by michel-kraemer** [comment]
Did you try setting the `TERM` environment variable to `dumb` [1]? This should suppress the output. Let me know if it doesn't.

[1] https://stackoverflow.com/questions/17942819/how-can-i-get-clean-gradle-output-on-travis-ci
