### ISSUE TITLE
java.io.IOException: Invalid argument

### ISSUE THREAD

**Issue by guobosheng** [michel-kraemer/gradle-download-task#123]
`task downloadFile(type: Download) {
    src 'http://192.168.1.6:8090/call.ashx?cpd=generateOfflineData&appId=hangaroa_weixin'
    dest buildDir
}`

`D:\Documents\AgpAutoBuild>gradle downloadFile

FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: Invalid argument
> Invalid argument

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s`

**Comment by michel-kraemer** [comment]
Thanks for reporting. Can you run the build again with `--stacktrace` as it says in the message and post the full stack trace here so we can investigate the issue better?
