### ISSUE TITLE
Support Gradle 5

### ISSUE THREAD

**Issue by remmeier** [michel-kraemer/gradle-download-task#126]
It seems that the Gradle Task API introduced a `getTimeout` method which clashes with the one of this plugin in the Download Task. The Gradle one requires a Property<Duration>.

**Comment by michel-kraemer** [comment]
Interesting. I'll investigate this and get back to you.

**Comment by michel-kraemer** [comment]
In the upcoming gradle-download-task version 4.0.0, the `timeout` property will be replaced by `connectTimeout` and `readTimeout` providing you with more control about timeouts and avoiding the name clash with the `timeout` property in Gradle 5.
