### ISSUE TITLE
Task does not work with gradle 5.1

### ISSUE THREAD

**Issue by apogrebnyak** [michel-kraemer/gradle-download-task#128]
With attached project (it is configured with Gradle 5.0 wrapper) just run

```
./gradlew
```

See that it completes, downloading and extracting tomcat ZIP distribution

Now upgrade wrapper to 5.1 and run a clean build again

```
./gradlew clean
./gradlew wrapper --gradle-version 5.1 --distribution-type all
./gradlew
```

IT FAILS with the following message:
```
> Task :downloadAndUnzipFile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloadAndUnzipFile'.
> Cannot expand ZIP '/path/to/test-download/build/apache-tomcat-8.5.37.zip' as it does not exist.
```

After some examination, you can see that `build` directory is not created at all

**Comment by apogrebnyak** [comment]
Could not find a way to attach a file.
Here is `build.gradle`

```
plugins {
   id 'de.undercouch.download' version '3.4.0' apply false
}

allprojects {
    apply plugin: 'base'
    apply plugin: 'de.undercouch.download'
}

task downloadZipFile(dependsOn: clean, type: Download) {
    src 'http://www.gtlib.gatech.edu/pub/apache/tomcat/tomcat-8/v8.5.37/bin/apache-tomcat-8.5.37.zip'
    dest file("${buildDir}/apache-tomcat-8.5.37.zip")
    onlyIfNewer false
}

task downloadAndUnzipFile(dependsOn: downloadZipFile, type: Copy) {
    from zipTree(downloadZipFile.dest)
    into buildDir
}

defaultTasks 'downloadAndUnzipFile'
```

Here is `settings.gradle`
```
pluginManagement {
    repositories{
        jcenter()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
}
```

In order to configure wrapper for 5.0, please use this command
```
gradle wrapper --gradle-version 5.1 --distribution-type all
```

**Comment by michel-kraemer** [comment]
Thanks for reporting. I'll investigate this and get back to you.

**Comment by michel-kraemer** [comment]
I did not find a corresponding bug report but this seems to be an issue with Gradle 5.1 and 5.1.1. Please upgrade to Gradle 5.2 and everything should work again.

Note that users who just want to download a file without a subsequent `Copy` task are not affected.
