### ISSUE TITLE
Is It Possible to Download a File Only if the Checksum Doesn't Match?

### ISSUE THREAD

**Issue by TobyPeepsMagoo** [michel-kraemer/gradle-download-task#130]
My team is using large Excel files for test purposes.  The largest of these files is over thirty megabytes in size, so downloading the entire file for every test run takes too much time.

Is there way using this plugin to only download files _if_ the Verify task fails?

**Comment by TobyPeepsMagoo** [comment]
After exploring the code for awhile, I came upon this code block in the DownloadExtension class

```
DownloadAction da = ConfigureUtil.configure(cl, new DownloadAction(project));
        try {
            da.execute();
        } catch (IOException e) {
            throw new IllegalStateException("Could not download file", e);
}
```
Does this block execute the download during Gradle's configuration phase?

**Comment by michel-kraemer** [comment]
> Is there way using this plugin to only download files _if_ the Verify task fails?

No, this is not possible. How should the plugin know which checksum the file on the server has without downloading it? Such a feature is usually implemented using Etags. See the `useETag` configuration property. Of course, this requires the server to also provide an Etag for your file (which could actually be a checksum, by the way).

> Does this block execute the download during Gradle's configuration phase?

This is the purpose of the `DownloadExtension`. You can use it if you want to download something immediately when the `DownloadExtension` is evaluated.
