### ISSUE TITLE
Dynamically build a package, with specific contents

### ISSUE THREAD

**Issue by KALIAKA2** [michel-kraemer/gradle-download-task#131]
Appreciate your work, Michael. Very impressive!

Here is my scenario. I have a Gradle project. This project doesn’t have any java code. All it has, is a ‘build.gradle’ file … that has many tasks to package other war/jar/libs/configs from certain source directories, and create a TAR.GZ file output. … this ‘build.gradle’ file is currently being used, before implementing DevOps. Now, after we have the Artifactory repository, where all these war/jar/libs/configs are stored in Artifactory, we want to update this ‘build.gradle’ file to fetch / download all the files from Artifactory …

•	I want to give options to produce 3 different package types – LIGHT / PARTIAL / FULL … meaning, LIGHT package will have a pre-defined set of files, PARTIAL package will have custom selection, FULL package will have everything
•	Gradle should fetch the files from Artifactory, according to the package type chosen (LIGHT/PARTIAL/FULL)
•	Is it possible to bring in such dynamism into a build.gradle file?

Please let me know.

**Comment by michel-kraemer** [comment]
Yes, this is possible. I suppose you're using a property to specify the package type? If yes, you can do something like this:

```gradle
task downloadFiles(type: Download) {
    def sources = ['http://example.com/url1']
    if (project.hasProperty("type")) {
        if (type == "full" || type == "custom") {
            sources << 'http://example.com/url2'
        }
        if (type == "full") {
            sources << 'http://example.com/url3'
        }
    }
    src(sources)
    dest buildDir
}
```

Then, you will be able to create the `full` package with:

    gradle downloadFiles -Ptype=full
