### ISSUE TITLE
[ INFO ] execute script after download

### ISSUE THREAD

**Issue by kekkokk** [michel-kraemer/gradle-download-task#135]
Hi guys, 
I wonder if there is any way to run a command line script only if the donwload succeeded.
I mean I have set the prebuild task dependent to a download task but with `onlyIfModified true`, so I need also to extract the archive of sources downloaded before the build start but only if a newer version was downloaded. is there any way to do this? 
thanks!
Francesco.

**Comment by michel-kraemer** [comment]
If you want to run something after the download task you have to create another task and make it depend on the download task using `dependsOn`. You can run a command line script with the `Exec` task [1] and extract the contents of an archive with the `Copy` task [2]. You may adapt the `unzip.gradle` example build script [3]. I think it already goes in the right direction.

Let me know if this answers your question or if you need more help. Thanks.

Cheers,
Michel

[1] https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html
[2] https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html
[3] https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/unzip.gradle
