### ISSUE TITLE
Download file failed org.apache.http.client.ClientProtocolException

### ISSUE THREAD

**Issue by alexandrratush** [michel-kraemer/gradle-download-task#137]
My build file:

`import de.undercouch.gradle.tasks.download.Download

buildDir = '.gradle_build'

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'de.undercouch:gradle-download-task:3.4.3'
    }
}

apply plugin: 'de.undercouch.download'

defaultTasks 'download'

task download(type: Download) {
    username "your_gmail@gmail.com"
    password "your_password"
    src([
        'https://github.com/distriqt/ANE-PushNotifications/blob/master/lib/com.distriqt.PushNotifications.ane'
    ])
    dest '.'
}`

Error:

`Execution failed for task ':download'.
> org.apache.http.client.ClientProtocolException: Not Found`

**Comment by michel-kraemer** [comment]
The file does not exist on the server. Please check your URL.

**Comment by alexandrratush** [comment]
Hi, this file is in a private repository.

**Comment by alexandrratush** [comment]
Hi. How to solve this problem?

**Comment by javabrett** [comment]
Seems likely basic auth is not supported by GitHub.  You can check using `curl` or `wget`.

https://stackoverflow.com/q/20396329/452210 might help. Perhaps you can auth using API tokens in headers.
