### ISSUE TITLE
use Worker API

### ISSUE THREAD

**Issue by dulmandakh** [michel-kraemer/gradle-download-task#138]
Worker API introduced in Gradle 5.4.1 allows to execute work concurrently and asynchronously, and I think it might be useful to download files concurrently. It might be best to add support for it release 4.x version, since most users still use 3.x and it won't be a breaking change.

https://guides.gradle.org/using-the-worker-api/

Thank you

**Comment by michel-kraemer** [comment]
This is a good idea but I cannot implement it yet as we still need to support Gradle versions older than 4.10.3 (that should be the minimum version for the worker API).  I'll pin this issue for the time being and implement the feature at a later point in time.

**Comment by ZacSweers** [comment]
@michel-kraemer out of curiosity, why support such an old API?

**Comment by michel-kraemer** [comment]
@ZacSweers You're right. I just deprecated Gradle 2.x up to 4.x as well as Java 7. This will allow me to do some cleanup in gradle-download-task 5.0.0. :+1:

**Comment by dulmandakh** [comment]
@michel-kraemer how about dropping 5.x too, then support only 6.x and 7.x?

**Comment by cortinico** [comment]
Hey @michel-kraemer are there some updates on this front?
Is this task up for grab or are you planning to work on it?

**Comment by michel-kraemer** [comment]
@cortinico Sorry, there are no updates on this at the moment. Do you have any specific need for this feature?

**Comment by cortinico** [comment]
> Do you have any specific need for this feature?

Yup we use `gradle-download-task` inside `react-native` for a series of native libraries that needs to be downloaded during the build. The download step is on the critical path, and we do have to download [six libraries](https://github.com/facebook/react-native/blob/6be46b0bb59f2d88bc78e9a72db672bd55914fa7/ReactAndroid/build.gradle#L169-L178). Having them run in parallel would be a great improvement.

I'm wondering what was the plan here. If you're planning on working on Worker API support, you're welcoming external contributions or should we create our own wrapper

**Comment by michel-kraemer** [comment]
OK. Sounds good. I will reprioritise my efforts then!

> I'm wondering what was the plan here.

The long-term plan was to deprecate support for Gradle versions 2.x-4.x and then eventually implement support for the worker API (besides other improvements, which would then become possible) after a reasonable period of time. I just checked the commit log and this thread here and noticed that 2.x-4.x have been deprecated in July 2020 already! 😳 So, I think it's really time to move on now.

I will start refactoring as soon as possible. You can expect the first commits in the next few days. I'll keep you informed about the progress.

**Comment by michel-kraemer** [comment]
@cortinico I've just published a snapshot of the upcoming gradle-download-task 5.0.0 with support for the worker API and parallel downloads.

If you want, you can try it out as follows:

```gradle
buildscript {
    repositories {
        maven {
            url 'https://oss.sonatype.org/content/groups/public'
        }
    }
    dependencies {
        classpath 'de.undercouch:gradle-download-task:5.0.0-SNAPSHOT'
    }
}

apply plugin: 'de.undercouch.download'
```

The actual usage of the plugin has not changed. Your build script should automatically download files in parallel with this version.

The plugin requires Gradle 5.x and Java 8 now. 

I'll make some more adjustments and improvements and release 5.0.0 in the next few weeks. I'll keep this issue open until then for feedback and further discussion.

**Comment by dulmandakh** [comment]
Thanks @michel-kraemer. React Native uses Gradle 7.x and JDK 11, so it would be ok.

**Comment by michel-kraemer** [comment]
Version 5.0.0 has just been released. I'm closing this issue now. Please let me know if you have any more ideas or feedback!

**Comment by cortinico** [comment]
> Version 5.0.0 has just been released. I'm closing this issue now. Please let me know if you have any more ideas or feedback!

Thank you very much for doing it 🙏
