### ISSUE TITLE
Question: Usage inside a plugin

### ISSUE THREAD

**Issue by duschata** [michel-kraemer/gradle-download-task#140]
Hello,
I would like to use the plugin inside another plugin like this:

```
  class CopyTemplatesPlugin implements Plugin<Project> {


    void apply(Project project) {

        def extension = project.extensions.create('copyTemplatesSettings', CopyTemplatesPluginExtension)

        project.tasks.create(name: 'copyFoo', type: Download) {

            group "documentation"

            // works but extension settings (to configure this dynamical) are not available in the configuration phase
            // src extension.template

            src 'https://somewhere.de/index.html'
            dest 'tmp'

            group "documentation"


        }

        project.task('copyBar', type: Download) {

            group "documentation"

            doLast {
                download {
                    src extension.url
                    dest 'tmp'
                }
            }
        }
    }
}


```

the copyFoo Task works but the extension object is not available. The copyBar Task reads the extension closure but throws an exception "Please provide a download source"
How can I solve this?

**Comment by michel-kraemer** [comment]
The `copyBar` task has an additional `download` block inside of it. Do you need that? Either remove the `type: Download` or the `download` block. This should at least solve the problem with the "Please provide a download source" error.

**Comment by duschata** [comment]
thanks, I've tried out both. 

```
project.task('copyBar', type: Download) {


            group "documentation"

            doLast {
                src 'https://somewhere.de/index.html'
                dest 'tmp'
            }
        }
```
terminates with the same exception

```
 project.task('copyBar') {
            group "documentation"
            doLast {
                download {

                    src 'https://toms-toy.de/index.html'
                    dest 'tmp'
                }
            }
        }
```
throws another exception:

`Could not find method download() for arguments [de.docs_as_co.toolchain.common.gradle.CopyTemplatesPlugin$_apply_closure2$_closure3$_closure4@63d26532] on task ':copyBar' of type org.gradle.api.DefaultTask.
`

could that be related to the build.gradle in my buildSrc Folder? 

```
dependencies {
    compile gradleApi()
    compile localGroovy()
[...]

    compile 'de.undercouch:gradle-download-task:3.4.3'
}
```

**Comment by michel-kraemer** [comment]
I don't know about the second case, but the first one is pretty clear. You have to define `src` and `dest` in the task definition and not in the `doLast` block. That's too late.

**Comment by duschata** [comment]
I have no clue why the second example is not working. To reproduce this, you can checkout 
https://github.com/duschata/reproduceDownloadError.git

the download() function call in the closure of the build.gradle has another scope as the download function called from the Plugin project-object. I don't know why

**Comment by duschata** [comment]
the download() function call in the closure of the build.gradle is executed by 
``` 
public DownloadExtension configure(@SuppressWarnings("rawtypes") Closure cl) {
        DownloadAction da = ConfigureUtil.configure(cl, new DownloadAction(project));
        try {
            da.execute();
        } catch (IOException e) {
            throw new IllegalStateException("Could not download file", e);
        }
        return this;
    }
```
at the  da.execute(); call
but this function is not available inside the plugin...

**Comment by duschata** [comment]
to make it a litte bit clearer: 
at this point (in my plugin) 
```
        project.task('copyBar') {
            group "documentation"
            doLast {
                download {

                    src 'https://somewhere.de/index.html'
                    dest 'tmp'
                }
            }
        }
```
there is no DownloadPlugin available (because it's not set by the closure delegate). So the thrown exception is absolute correct: type org.gradle.api.DefaultTask has no method "download"
If we make the DownloadPlugin available for the closure delegate (...type: Download) the action.execute() function in your script parses the closure and does not find a src, dest and so on and says goodby by throwing an exception. The point download inside the doLast block is never reached. But if this point could be reached, there is no function with the download(Closure closure) signature in your Download.class, the script will also terminate. The process in the build.gradle is different. The block is parsed by the DownloadExtension, founds the download part and delegates it to the annotated  @TaskAction.  A found a quickfix (very quick and dirty) by skipping the parsing in the configuration phase and it works for me. Please have a look at it to understand my problem (maybe there is a better solution) https://github.com/duschata/reproduceDownloadError/tree/quickfix

**Comment by michel-kraemer** [comment]
Why don't you just use it like this?

```gradle
project.task('downloadTemplatePlugin', type: Download) {
    group "documentation"
    src 'https://somewhere.de/index.html'
    dest tmp
}
```

**Comment by duschata** [comment]
thanks for answering, see at my first comment. During the configuration-phase there is no access to the extension object which I need.

**Comment by michel-kraemer** [comment]
I read the whole thread again and I understand that the extension object is not available. My question is: why do you need the extension object at all? Why can't you use `type: Download`?

**Comment by duschata** [comment]
I would like to "wrap" the plugin by an own plugin. Inside the configuration-closure (extension) of my plugin I would like to provide a set of plugin-specific defined download sources. There should be no possibility for the user to use other URLs than the predefined.

**Comment by michel-kraemer** [comment]
So, what you are trying to do is to write your own extension that executes the extension of gradle-download-task. Is that correct? If yes, you may call the `DownloadAction` class yourself like it is done in `DownloadExtension`:
https://github.com/michel-kraemer/gradle-download-task/blob/master/src/main/java/de/undercouch/gradle/tasks/download/DownloadExtension.java

**Comment by michel-kraemer** [comment]
... or maybe subclass `DownloadExtension`.
