### ISSUE TITLE
Support Provider as lazy-resolution-interface

### ISSUE THREAD

**Issue by octylFractal** [michel-kraemer/gradle-download-task#142]
The Kotlin DSL is a popular option for many users of Gradle, but it makes the lazy-evalutation of `src` much harder to use, because rather than being able to use a standard Gradle interface such as `Provider<T>`, we must wrap our functions in a Closure object. It would be much nicer for both Kotlin & Java if a `Provider<T>` was also resolved like a Closure currently is.

**Comment by michel-kraemer** [comment]
Sounds reasonable to me. Which `Provider` class do you mean? `org.gradle.api.provider.Provider`? Can you provide sample scripts for the current version and how you would like to use it instead? Thanks!

**Comment by mike-neck** [comment]
+1

I really want to pass `Provider<T>` to `DownlaodTask#dest(Object)`.

My plugin depends on a download task for my task to run jar file which is downloaded by the `DownloadTask`. To avoid downloading the same file over and over, the plugin configures the task to download it to any directory other than `build` determined by user. In this case my extension object becomes like this.

```kotlin
open class MyExtension(project: Project) {
  // this is subclass of Property<RegularFile> that can be converted into Property<File>
  val jarFile: RegularFileProperty 
  init {
    this.jarFile = project.objects.fileProperty()
  }
}
```

And my plugin code becomes...

```kotlin
open class MyPlugin: Plugin<Project> {
  override fun apply(project: Project) {
    val extension = project.extensions.create("my", MyExtension::class.java, project)
    project.tasks.create("downloadJar", Download::class.java) {
      it.dest(extension.jarFile.asFile)       
    }
    // omit other code
  }
}
```

and user's script becomes...

```groovy
plugins {
  id 'my-plugin'
}

my {
  jarFile.set(file("$projectDir/my-jar"))
}
```

At the phase of applying plugin, user's configuration is not reflected in the extension object. Therefore this build cannot pass the destination directory to the download task.

**Comment by michel-kraemer** [comment]
Thanks for the additional information. I implemented this feature in 36cf9d5 and uploaded a new snapshot 4.0.3-SNAPSHOT. Let me know if this solves your problem. If yes, I can release a new version.

**Comment by mike-neck** [comment]
Thanks!! I tried 36cf9d5, and it works well. I think it's great work.

**Comment by michel-kraemer** [comment]
Great. Thanks for the feedback. I'll release a new version until the end of the week.
