### ISSUE TITLE
Option to ignore failing downloads with status 404

### ISSUE THREAD

**Issue by dpolivaev** [michel-kraemer/gradle-download-task#145]
Hello, I do not have the directory listing and need to try if certain files from my list are available or not. In the second case I get status 404 and it is expected. Hot can I configure the task not to fail on such errors?

Regards
Dimitry

**Comment by michel-kraemer** [comment]
You could use the download extension instead of the task like this:

```gradle
try {
    download {
        src "http://......."
        dest buildDir
    }
} catch (Exception e) {
    logger.warn("Could not download file.")
}
```

Please let me know if this helps.
