### ISSUE TITLE
Download task always up to date with gradle-download-task 4.x

### ISSUE THREAD

**Issue by jeremyjliu** [michel-kraemer/gradle-download-task#147]
Multiple file download task seems to always be up to date and thus does not download any files. Same task declaration works on 3.4.3, i.e. last 3.x release.

Versions: gradle-download-task:4.0.0+ (tested on 4.0.0 and 4.0.4)

Task:
```
task fetchAssetBundles(type: Download) {
    doFirst {
        src([
                ...,
                ...
        ])
        dest buildDir

        acceptAnyCertificate true
        onlyIfNewer true
    }
}
```

Output snippet:
```
Selected primary task 'fetchAssetBundles' from project :
Tasks to be executed: [task ':fetchAssetBundles']
:fetchAssetBundles (Thread[Execution worker for ':' Thread 2,5,main]) started.

> Task :fetchAssetBundles UP-TO-DATE
Custom actions are attached to task ':fetchAssetBundles'.
Caching disabled for task ':fetchAssetBundles' because:
  Caching has not been enabled for the task
Task ':fetchAssetBundles' is not up-to-date because:
  Task.upToDateWhen is false.
```

Gradle version:
```
$  ./gradlew --version

------------------------------------------------------------
Gradle 5.6.4
------------------------------------------------------------

Build time:   2019-11-01 20:42:00 UTC
Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.4 (Azul Systems, Inc. 11.0.4+11-LTS)
OS:           Mac OS X 10.14.6 x86_64
```

**Comment by michel-kraemer** [comment]
Can you please give me some more details. What do you mean with "seems to always be up to date". What is the expected behaviour? Have the files on the server changed and you want to overwrite the local files? Or are the files not downloaded at all in the first place?

I see that you get a warning regarding "custom actions". Please try to remove the `doFirst` statement. It's not necessary and probably the root of your issue.

**Comment by jeremyjliu** [comment]
Files were not downloaded at all in the first place. Yes, you are right, the problem was with the doFirst block which was necessary due to another plugin that injected information at runtime.
