### ISSUE TITLE
Incomplete downloads are not retried

### ISSUE THREAD

**Issue by ZakTaccardi** [michel-kraemer/gradle-download-task#149]
I can download a file, cancel it halfway (kill the Gradle daemon). When I run the download task again, it thinks the file has already been downloaded, even if it is a incomplete download.

```groovy
TaskProvider downloadKtLintExectuable = tasks.register("downloadKtLintExectuable", Download) {
    src "https://github.com/pinterest/ktlint/releases/download/0.35.0/ktlint"
    onlyIfModified true
    useETag true

    acceptAnyCertificate true
}
```

How can we account for this?

**Comment by ZakTaccardi** [comment]
One way could be to pass in a checksum as input to the task to retry if it fails the checksum check?

My ideal goal would be to download a file and its checksum, and retry the download if the checksum does not match

**Comment by michel-kraemer** [comment]
How about the `tempAndMove` flag? If you set this flag to `true`, gradle-download-task will create a temporary file and only move it to the final destination if the download was successful.

Let me know if this helps or if you need more assistance.

**Comment by ZakTaccardi** [comment]
Brilliant solution, I love it!
