### ISSUE TITLE
Kotlin DSL support for the "download" extension

### ISSUE THREAD

**Issue by bigpuritz** [michel-kraemer/gradle-download-task#150]
Hi,

it would be nice to have full Kotlin DSL Support out of the box for the "download" Extension.

For now it is only possible with some ugly code like this:

```kotlin
tasks.register("downloadFile") {
    doLast { 
        download.configure(
                delegateClosureOf<DownloadAction> {
                    src("http://www.example.com/index.html")
                    dest(buildDir)
                }
        )
    }
}
```

As a workaround i can create a Kotlin Extension by my own in the **build.gradle.kts** script like this. But this should be a part of the plugin.

```kotlin
fun Task.download(action: DownloadAction.() -> Unit) =
        download.configure(delegateClosureOf(action))

tasks.register("downloadFile") {
    doLast { 
        download {
            src("http://www.example.com/index.html")
            dest(buildDir)
        } 
    }
}
```

**Comment by michel-kraemer** [comment]
Thanks for the request. I'll see what I can do and get back to you.

**Comment by jiridanek** [comment]
I've been happily using the download plugin from Kotlin build script like this. I used version 4.0.4 of the plugin and Gradle 6.2. No extensions necessary.

``` kotlin
tasks {
    val downloadZipFile by registering(Download::class) {
        src("https://github.com/michel-kraemer/gradle-download-task/archive/1.0.zip")
        dest(File(buildDir, "1.0.zip"))
    }
}
```

**Comment by Fleshgrinder** [comment]
The following extension allows you to simply use `download` anywhere as intended:

```kotlin
fun Project.download(action: DownloadAction.() -> Unit) {
    download.configure(delegateClosureOf(action))
}
```

It's also possible to define it slightly differently and use named arguments instead of a closure:

```kotlin
fun Project.download(
    src: String, 
    dst: String, 
    overwrite: Boolean? = null,
    quiet: Boolean? = null,
    onlyIfModified: Boolean? = null,
    onlyIfNewer: Boolean? = null,
    // and so on ...
) {
    download {
        src(src)
        dest(dst)
        overwrite?.let(this::overwrite)
        quiet?.let(this::quiet)
        onlyIfModified?.let(this::onlyIfModified)
        onlyIfNewer?.let(this::onlyIfNewer)
        // and so on ...
    }
}

tasks {
    register("foo") {
        doLast {
            download("http", "/path", quiet = true)
        }
    }
}
```

**Comment by elect86** [comment]
@jiridanek I guess that's another thing

**Comment by michel-kraemer** [comment]
@rafiwew I'm not completely sure what you mean. If you found a bug in gradle-download-task or have a feature request or a general question, please open a new issue instead of commenting on old ones. I will be more than happy to answer your request if you can provide more information. Thanks for your understanding.
