### ISSUE TITLE
Task fails if use overwrite option while downloading a build.

### ISSUE THREAD

**Issue by craftizmv** [michel-kraemer/gradle-download-task#154]
@michel-kraemer I am trying to download some artifact from artifactory server. 

task downloadTask(type: Download) {

    def userHome = System.getProperty("user.home")

    src "${SRC_URL}"
    dest new File("${userHome}/native-libs", "Some.zip")
    overwrite false
}

When I am using overwrite is false, my understanding is it will detect if the file is present in the path or not if the file is not present it will go-ahead for the download if it is present then it will ignore re-download. But when I use this option then if the file is not present it Task fails straight away it doesn't go ahead to download that file.
Is it a bug or is there any flaw in my understanding?

**Comment by michel-kraemer** [comment]
Your understanding is correct. What error message do you get?

**Comment by mayankcool786** [comment]
I checked that it works correctly if I remove the .gradle file from my project. Looks like gradles caches the setting but does not get updated if I delete the file.

**Comment by michel-kraemer** [comment]
Sorry for my late response. So, did this solve your problem? It doesn't seem to be a bug in gradle-download-task, or is it?
