### ISSUE TITLE
The plugin should support the Gradle configuration cache

### ISSUE THREAD

**Issue by eskatos** [michel-kraemer/gradle-download-task#156]
The configuration cache is a feature that significantly improves build performance by caching the result of the configuration phase and reusing this for subsequent builds.

Implementing support for the configuration cache in this plugin would improve users experience.

See https://docs.gradle.org/nightly/userguide/configuration_cache.html

The configuration cache will be introduced in Gradle 6.6.
But this can already be tested using `6.6-milestone-2`.

Currently, running the integration tests with a Gradle 6.6-milestone-2 and the configuration cache enabled produce the following problems report: 
[download-plugin-problems.zip](https://github.com/michel-kraemer/gradle-download-task/files/4809586/download-plugin-problems.zip)

Both the `Download` and `Verify` tasks use the `Project` object at execution time and indirectly hold references to it. This prevents the use of this plugin with the configuration cache enabled. See https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

**Comment by michel-kraemer** [comment]
Fixed by #157
