### ISSUE TITLE
Downloading with onlyIfNewer prints "Download URL" when nothing is being downloaded

### ISSUE THREAD

**Issue by veyndan** [michel-kraemer/gradle-download-task#160]
Whenever I use `onlyIfNewer true`, "Download $url" is displayed on subsequent runs when the Gradle task is correctly not downloading anything. This was a bit confusing when trying to optimise the build speed of my project, as I initially thought that this Gradle task was downloading from the url on every build, which turned out to not be the case.

## Source Code

```groovy
apply plugin: 'de.undercouch.download'

task updateDependencies {
  def intellijCoreZip = new File(buildDir, "intellij-core-${ideaVersion}.zip")

  download {
    src "https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.2/ideaIC-2020.1.2.zip"
    dest intellijCoreZip
    onlyIfNewer true
  }

  copy {
    from zipTree(intellijCoreZip)
    into new File("$buildDir/intellij-core")
  }
}
```

### Middle of Execution

```bash
> Configure project :
Download https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.2/ideaIC-2020.1.2.zip
<-------------> 0% CONFIGURING [7s]
> root project > 62.09 MB/507.83 MB downloaded
```

### Result of Execution

```bash
> Configure project :
Download https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.2/ideaIC-2020.1.2.zip

BUILD SUCCESSFUL in 54s
```

### Middle of Execution

The line `> root project > x MB/y MB downloaded` is correctly never displayed.

### Result of Execution

❓  `Download https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.2/ideaIC-2020.1.2.zip` is printed even though nothing is being downloaded.

```bash
> Configure project :
Download https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.2/ideaIC-2020.1.2.zip

BUILD SUCCESSFUL in 12s
```

**Comment by michel-kraemer** [comment]
I understand what you mean but gradle-download-task actually performs an HTTP request if you only set `onlyIfNewer`. It sends the `If-Modified-Since` and then relies on the server to return `304 Not Modified`. Waiting for the response from the server before printing the message IMHO doesn't make sense because establishing the connection could be considered part of the download.

I'm closing this issue. Please do not hesitate to comment here or reopen the issue if you have a good idea.

**Comment by veyndan** [comment]
Okay that makes sense. What do you think of just having an additional log message in the case that `304 Not Modified` is returned? For example, something along the lines of:

```
Download https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.2/ideaIC-2020.1.2.zip
Contents of https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.2/ideaIC-2020.1.2.zip not modified. Skipping download.
```

**Comment by michel-kraemer** [comment]
I just noticed that you're using the download extension in your `updateDependencies` task. This means that Gradle will always execute the task (regardless of any previous result) and that there is no way to tell it whether the task was up to date or not.

I recommend using two separate tasks for downloading and unzipping instead:

```gradle
task downloadZipFile(type: Download) {
    src "https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.2/ideaIC-2020.1.2.zip"
    dest new File(buildDir, "intellij-core-${ideaVersion}.zip")
    onlyIfNewer true
}

task downloadAndUnzipFile(dependsOn: downloadZipFile, type: Copy) {
    from zipTree(downloadZipFile.dest)
    into new File("$buildDir/intellij-core")
}
```

If you execute `gradle downloadAndUnzipFile` twice, you will get the following output the second time:

```
> Task :downloadZipFile UP-TO-DATE
```

I hope this helps.

**Comment by veyndan** [comment]
Thank you @michel-kraemer, that looks like exactly what I was looking for! 🙏
