### ISSUE TITLE
enhance checksum check

### ISSUE THREAD

**Issue by elect86** [michel-kraemer/gradle-download-task#165]
Hey,

it's common to have the checksum on the same url, plus the corresponding algorithm extension, eg `.sha256`

therefore I'd propose to offer another argument on `::src`, accepting the postfix to automatically download the corresponding checksum file, extracting the checksum and compare that against the calculated checksum from the main download file

```
download {
   src(".../linux-x64_bin.tar.gz", checksum = "sha256") // .../linux-x64_bin.tar.gz.sha256
   ...
}
```

Also, with kotlin, users may benefit from named argument, if you are interested in that, I can provide a PR (I might combine it with https://github.com/michel-kraemer/gradle-download-task/issues/150 as well and take 2 pigeon with one stone :smile: )

**Comment by michel-kraemer** [comment]
@elect86 That's a very good idea indeed. I'll pin this issue so I can implement it later.

Pull requests are more than welcome!! I'm looking forward to your contribution!

**Comment by slonopotamus** [comment]
How does downloading checksum _from the same source_ as checksummed data add any security? If source is compromised and gives you malicious data, it will also give you a proper checksum for it.

**Comment by michel-kraemer** [comment]
@slonopotamus Checksum files are not meant to provide additional security. They are typically used to detect transmission errors. Security is usually provided by the transfer protocol (e.g. HTTPS).
