### ISSUE TITLE
JCenter and Maven Central serving two different artifacts for 4.1.1

### ISSUE THREAD

**Issue by big-guy** [michel-kraemer/gradle-download-task#166]
Hi!

We have dependency verification enabled in our build and when updating to the latest version of Kotlin (1.5.20), we started seeing verification failures:
https://ge.gradle.org/s/dt6v732iuevd2

The Kotlin dependency is now bringing in a newer version of this plugin:
https://ge.gradle.org/s/dt6v732iuevd2/dependencies?dependencies=de.undercouch&expandAll&focusedDependency=Wzc4LDAsNzYzMSxbMTksMCxbMjNdXV0&focusedDependencyView=versions

The dependency verification report says that the signature doesn't match the jar file.

I took a look on Maven Central and downloaded the files from:

https://repo1.maven.org/maven2/de/undercouch/gradle-download-task/4.1.1/

gradle-download-task-4.1.1.jar -> 5da00a4a96829700216768887a8f3051 (MD5)
gradle-download-task-4.1.1.jar.asc -> 9889ae9893f6227893ee0828139c687a (MD5)

We have JCenter mirrored to our own repository, but JCenter is currently serving the same artifacts:

https://repo.gradle.org/artifactory/libs/de/undercouch/gradle-download-task/4.1.1/

gradle-download-task-4.1.1.jar -> 93578a8acb236688e2aebf33519b1dd2 (MD5)
gradle-download-task-4.1.1.jar.asc -> 9889ae9893f6227893ee0828139c687a (MD5)

This seems to be saying that the signature files are the same for both repositories, but the jar files _are_ different somehow.

When I compared the jars, they seem to have identical contents, so I think the differences are not from something malicious. I'm not sure how JCenter and Maven Central wound up with two different jars, do you?

This is going to cause headaches/confusion whenever someone runs into this. I checked 4.0.4 and 4.1.0 and they looked identical.

I've attached the jars here as well (rename from .zip) in case one or the other repository changes behavior.

Could you contact JFrog and see if they can fix something on their side? 

Or could you publish a 4.1.2? 

Thanks!

[From Maven Central](https://github.com/michel-kraemer/gradle-download-task/files/6743200/GOOD-gradle-download-task-4.1.1.jar.zip)
[From JCenter](https://github.com/michel-kraemer/gradle-download-task/files/6743201/BAD-gradle-download-task-4.1.1.jar.zip)

**Comment by michel-kraemer** [comment]
Thanks for bringing this up. Since JCenter is read-only now [1], I think the only possible solution is to publish a 4.1.2 to Maven only. I will try to do this within the next days.

[1] https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by michel-kraemer** [comment]
gradle-download-task 4.1.2 has just been released to Maven Central and the Gradle plugin portal (alternative Maven URL: https://plugins.gradle.org/m2/).
