### ISSUE TITLE
Perform downloadFile task during build in android

### ISSUE THREAD

**Issue by gargVader** [michel-kraemer/gradle-download-task#167]
I want to run my downloadFile task when an android app is built. How can I do it?

**Comment by michel-kraemer** [comment]
It's hard to say without knowing how you actually build your app. In Gradle, you can specify task dependencies using `dependsOn` [1]. Maybe this is what you are looking for?

[1] https://docs.gradle.org/current/userguide/more_about_tasks.html

**Comment by gargVader** [comment]
I was able to do it. 🥂
```
task downloadFile(type: Download) {
    src  '..........'
    dest '.........'
}
afterEvaluate {
    preBuild.dependsOn downloadFile
}
```
