### ISSUE TITLE
How can I download files more dynamically?

### ISSUE THREAD

**Issue by gargVader** [michel-kraemer/gradle-download-task#168]
- Presently, I just hardcode the `src url`. I wish to fetch the `src url`  from somewhere it has been defined. 
- Also while sending request to server, I usually use `httpURLConnection.setRequestProperty("X-Client-Id", clientId);`. Can I do something similar here too?

**Comment by michel-kraemer** [comment]
Please have a look at the following web page:
https://michelkraemer.com/recipes-for-gradle-download/

I think what you're looking for is recipe 4 (Custom HTTP headers) and recipe 7 (Groovy closures for `src` and `dest`).

**Comment by gargVader** [comment]
My `src` has been defined in one of the `.java` file and I want to use the value from there. Is it possible?

**Comment by michel-kraemer** [comment]
I would put the URL into a configuration file from where it can be read from both the Java file and your build script.
