### ISSUE TITLE
Cannot resolve download inside buildSrc

### ISSUE THREAD

**Issue by ThanosFisherman** [michel-kraemer/gradle-download-task#169]
Hi, I'm trying to remove some clutter from my app level build gradle file and move all of my tasks to buildSrc module.

The problem I'm facing is that the Download tasks cannot be resolved inside buildSrc whereas in app level gradle file it works fine.

This is my code
```kotlin
fun Project.includeTasks() {

    tasks.register<de.undercouch.gradle.tasks.download.Download>("downloadSomething") {

    }
}
```
Any ideas?

**Comment by michel-kraemer** [comment]
Where did you specify your dependency to gradle-download-task? I haven't tried it myself, but AFAIK you have to add it to a separate `build.gradle` file in your `buildSrc` folder. See the following links for more information:
https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources
https://stackoverflow.com/questions/34502101/how-can-i-use-third-party-dependencies-in-custom-task-under-buildsrc-in-gradle

Let me know if this helps.

**Comment by ThanosFisherman** [comment]
Hi, 

Thank you so much for the links. Upon reading the doc I thought that I only had to add the plugin inside `plugins {} ` block but turns out that I also need to include the dependency itself.

So this is how my `build.gradle.kts` in my `buildSrc` now looks like:

```kotlin
plugins {
    `kotlin-dsl`
    `java-gradle-plugin`
    id ("de.undercouch.download") version "4.1.2" //This is the only thing I added before
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    implementation("de.undercouch:gradle-download-task:4.1.2") //Apparently I need this here too
    testImplementation(gradleTestKit())
    testImplementation("junit:junit:4.13.1")

}
```
Works like a charm now. Using gradle 7.1.1 Thanks again :)
