### ISSUE TITLE
Add lazy evaluation for src and dest configuration

### ISSUE THREAD

**Issue by pgelinas** [michel-kraemer/gradle-download-task#18]
Most Gradle Tasks are capable of lazily evaluating their configuration just before execution, but the Download task isn't. So doing something like documented in the [user guide](https://www.gradle.org/docs/current/userguide/custom_plugins.html#N16B7E) isn't possible. I'd like to be able to pass a closure to src and dest so it is evaluated just before execution and therefore control the url with a variable that is set elsewhere in the build script, a bit like:

```groovy
task('downloadReleng', type: Download) { 
   src { "${baseUrl}/${version}" }
   dest { "${baseDest}/${version}" }
}
```

I want to be able to do that so that a plugin that provides a download task can be configured easily. Since the download task is configured during the plugin.apply call but the variables are not properly defined yet, this doesn't work. The workaround is to declare the task but configure it in an afterEvaluate block, which solves my issue but might not be ideal.

**Comment by michel-kraemer** [comment]
Thanks for this request. The fix is on master now.

Cheers,
Michel
