### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by slychops** [michel-kraemer/gradle-download-task#194]
Hi there,

I'm trying to connect an environment behind a connected VPN. Getting this error below. Have access to the file/s currently, but not in the gradle task. Any idea here?

Execution failed for task ':downloadFile'.
> A failure occurred while executing de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction
   > javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request

**Comment by michel-kraemer** [comment]
I'm not sure if this issue is related to gradle-download-task. Which Java version are you using?

**Comment by slychops** [comment]
Indeed, played around with a few other options and it's not related to the gradle download task. The issue is that gradle doesn't have a clear way to disable SSL verification. (like curl has the --skip-ssl-validation command).

**Comment by slychops** [comment]
Awesome thanks for response and those links. It's working now. `acceptAnyCertificate` seems to be working out the box though, so I must have just been doing something very stupid.
