### ISSUE TITLE
Download task not compatible with configuration cache

### ISSUE THREAD

**Issue by charleskorn** [michel-kraemer/gradle-download-task#199]
I have a project that uses the `Download` task. 

If I run the build with the configuration cache disabled, everything works as expected.

If I run the build with the configuration cache enabled (with the `--configuration-cache` CLI option to `./gradlew`), I get the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field 'action' from type 'de.undercouch.gradle.tasks.download.Download': error writing value of type 'de.undercouch.gradle.tasks.download.DownloadAction'
> Configuration cache state could not be cached: field 'cachedDestLock' from type 'de.undercouch.gradle.tasks.download.DownloadAction': error writing value of type 'java.util.concurrent.locks.ReentrantLock'
   > Unable to make field private final java.util.concurrent.locks.ReentrantLock$Sync java.util.concurrent.locks.ReentrantLock.sync accessible: module java.base does not "opens java.util.concurrent.locks" to unnamed module @446aaa52
```

I'm using version 5.0.1 of this plugin, Gradle 7.4 and OpenJDK 17.0.2.

**Comment by michel-kraemer** [comment]
Thanks for reporting this! It seems it only failed under Java 17. I created a bug fix release 5.0.2.

**Comment by charleskorn** [comment]
No worries, thanks for fixing this so quickly!

**Comment by sschuberth** [comment]
I'm actually seeing the same with Java 17, Gradle 8.6 and plugin version 5.5.0:

```
field this$0📋 of Build_gradle$generateSpdxLicenseEnum$2$3📋
    ⌄ bean of type Build_gradle$generateSpdxLicenseEnum$2$3📋
        ⌄ field action📋 of org.gradle.api.internal.AbstractTask$TaskActionWrapper📋
            ⌄ bean of type org.gradle.api.internal.AbstractTask$TaskActionWrapper📋
                ⌄ field actions📋 of de.undercouch.gradle.tasks.download.Download📋
                    ■task:utils:spdx-utils:generateSpdxLicenseEnum📋 of type de.undercouch.gradle.tasks.download.Download📋
```

So again the `actions` (Plural this time?) seems to be the culprit. Can we reopen?

**Comment by sschuberth** [comment]
> So again the `actions` (Plural this time?) seems to be the culprit. Can we reopen?

Nevermind, I believe the issue to be on my side, in the configuration of the custom task.
