### ISSUE TITLE
Check downloaded files for integrity

### ISSUE THREAD

**Issue by Alexander--** [michel-kraemer/gradle-download-task#20]
At least md5 would be nice.

**Comment by michel-kraemer** [comment]
Good idea! I'll try to implement this.

Cheers,
Michel

**Comment by michel-kraemer** [comment]
I added a `Verify` task. You can use it like this:

    task downloadFileToVerify(type: Download) {
        src 'http://www.apache.org/dist/spark/spark-1.3.0/spark-1.3.0.tgz'
        dest new File(buildDir, 'spark-1.3.0.tgz')
    }
    
    task verifyDownload(type: Verify, dependsOn: downloadFileToVerify) {
        src downloadFileToVerify.dest
        algorithm 'MD5'
        checksum '694B2863621FCDBBBA2777BF329C056C'
    }

Please let me know if this meets your requirements.

Cheers,
Michel

**Comment by Alexander--** [comment]
Thanks, that look good.
