### ISSUE TITLE
Download stalls when `max-workers==1` 

### ISSUE THREAD

**Issue by beatbrot** [michel-kraemer/gradle-download-task#205]
## What happens?

A download during configuration time that's using `download.run {}` stalls the configuration phase when `max-workers==1`. 

This is true for machines that only have one core, for containers with `--cpus 1` (e.g. in Kubernetes clusters), or for people who prefer running Gradle with `--max-workers=1`.

## Why does it happen?

The issue occurs due to this call:
https://github.com/michel-kraemer/gradle-download-task/blob/2fa1e89a8081da9a2028b2a9408f0757097c5ee1/src/main/java/de/undercouch/gradle/tasks/download/DownloadAction.java#L246

This call lets the current worker wait until another worker has processed the downloads that were enqueued in the worker thread. Since we only have one worker which is blocked by this call, no other worker will ever process the enqueued Jobs.

<details>

When running with `max-workers==1`, Gradle will enter `org.gradle.internal.resource.DefaultResourceLockCoordinationService#withStateLock` when enqueuing the download job. This will lead the current thread to stall in [`lock.wait()`](https://github.com/gradle/gradle/blob/aa5f947477c25b4ce6ba6581589e535370dffae4/subprojects/base-services/src/main/java/org/gradle/internal/resources/DefaultResourceLockCoordinationService.java#L51)

The main thread will stall on the `CompletableFuture` from above due to the `get()` call in [DownloadExtension#L29](https://github.com/michel-kraemer/gradle-download-task/blob/2fa1e89a8081da9a2028b2a9408f0757097c5ee1/src/main/java/de/undercouch/gradle/tasks/download/DownloadExtension.java#L29).

Now, if [`workerExecutor.await()`](https://github.com/michel-kraemer/gradle-download-task/blob/2fa1e89a8081da9a2028b2a9408f0757097c5ee1/src/main/java/de/undercouch/gradle/tasks/download/DownloadAction.java#L243) would be called, `DefaultResourceLockCoordinationService#notifyStateChange` would be called which releases the lock on which the worker thread waits.

If this doesn't happen though, both threads are waiting for a lock that only the respective other thread could release. This leads to a lockup.
</details>

## How to fix it?

When calling `download` from configuration time, we need to always call `workerExecutor.await()`, even on newer Gradle versions. This could be easily done by always forcing await when the `DownloadExtension` is used.

I already have the code for this and will happily submit a PR!

## How to reproduce?

Run `gradlew --max-workers=1` with the following `build.gradle` file:

```gradle
plugins {
    id "base"
    id "de.undercouch.download" version "5.0.2"
}

download.run {
    src 'https://example.com'
    dest 'out.txt'
}
```

**Comment by michel-kraemer** [comment]
Thanks for spotting this and for providing such a thorough analysis. Very much appreciated! 👍 

I've fixed the issue and released a new version 5.0.3.

**Comment by beatbrot** [comment]
I have to thank you for the quick fix and the immediate release :) This will help me a lot!

**Comment by michel-kraemer** [comment]
Oops. It seems I was too fast! I didn't let the unit tests run through. Please use 5.0.4 😉
