### ISSUE TITLE
SSLException: Connection Reset when migrating to 5.x

### ISSUE THREAD

**Issue by ossner** [michel-kraemer/gradle-download-task#211]
Hi!
I was tasked with refining our Gradle script, including the download of a single zip file.
However, when upgrading the version of the plugin to 5.x version from 4.1.2 and making the necessary changes to the run method, the download keeps crashing due to an SSLException, specifically `javax.net.ssl.SSLException: Connection reset`.

The task in question:
```
task downloadBundle {
    download.run {
        src "${externalArtifactoryURL}/Bundle/${bundleVersion}/Bundle.zip"
        dest file(bundleLocation + '.zip')
        username artifactoryUserAccount
        password externalArtifactoryPassword
    }
}
```

We also have a backup server (no SSL) that works fine, but I still want to be able to download from this server.
Thanks in advance!

**Comment by michel-kraemer** [comment]
Does the server use a self-signed certificate? Have you tried using the `acceptAnyCertificate` flag?

**Comment by ossner** [comment]
I forgot to mention that. Yes I tried using that flag, but it also didn't work.
As for the self signed certificate, I am unsure. How can I find that out?

**Comment by michel-kraemer** [comment]
Well, what happens if you open the URL in your browser?

**Comment by ossner** [comment]
Downloading/accessing the server from the browser works just fine, as does downloading with an older version of the plugin.

**Comment by michel-kraemer** [comment]
Do you happen to know which SSL/TLS version your server uses?

**Comment by ossner** [comment]
It's using TLS 1.2

**Comment by michel-kraemer** [comment]
This should work actually 🤔 I don't know... It's very hard to tell what's going on without access to the server. I'm almost out of ideas.

Is there a proxy involved maybe? If so, can you try to configure Gradle to skip the proxy for this server? (see docs: https://github.com/michel-kraemer/gradle-download-task#proxy-configuration)

**Comment by ossner** [comment]
Alright, so proxy settings are not necessary, however, I came across this [JFrog wiki article](https://jfrog.com/knowledge-base/how-to-resolve-unable-to-find-valid-certification-path-to-requested-target-error). Do you think that could be an issue with the newest plugin?

**Comment by michel-kraemer** [comment]
I'm not sure. As I said, without more information, it's really hard to debug this issue.

I created a small reproducer for you: [issue211.zip](https://github.com/michel-kraemer/gradle-download-task/files/8515571/issue211.zip)

Please edit the `Main.java` and change the host to your server. The run `./gradlew run -s` from the command line. It should create a file `download.log`. Send it to me via email. It will hopefully contain enough information to debug this issue. If possible, send me the full stacktrace of the exception you get too. Thanks!

**Comment by ossner** [comment]
Thank you for your time and effort on this issue. I've used the tool and looked at the output myself and contacted our DevOps team in order to check this out as I already have a sneaking suspicion that this is an issue on our end. I will definitely update this issue and send you the log if I get permission to do so.
Thanks again!

**Comment by michel-kraemer** [comment]
Sounds good. Looking forward to your feedback.
