### ISSUE TITLE
Download using basic auth with empty password fails after upgrading to 5.x

### ISSUE THREAD

**Issue by NielsDoucet** [michel-kraemer/gradle-download-task#215]
Sonarqube uses an authentication scheme with api tokens. The way to use this is by setting basic auth's username to the token and an empty password. (see also https://community.sonarsource.com/t/what-is-http-header-for-api-authentication/34117/2)
This worked when using version 4.x of this library:
```
task downloadFile(type: Download) {
    src 'https://our.sonarqube.instance/some-checkstyle-ruleset'
    dest buildDir
    username apiToken
    password ""
}
```
After upgrading to 5.x, we get a 401 using the exact same task configuration:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloadCheckstyleRulesetFromSonar'.
> A failure occurred while executing de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction
   > de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ClientProtocolException: HTTP status code: 401, URL: 
https://our.sonarqube.instance/some-checkstyle-ruleset
```

**Comment by michel-kraemer** [comment]
Thanks for reporting this. I was able to reproduce the issue. The problem is not the empty password but the fact that Sonarqube does not send a `WWW-Authenticate` header in its 401 response. Due to this, gradle-download-task does not know which authentication method to use. Version 4 always used preemptive authorization. This was disabled in version 5 because it might be a security issue to always include credentials in the first request.

I'm working on a fix. In the meantime, you can use a workaround. Simply replace `username` and `password` with a header:

```gradle
task downloadFile(type: Download) {
    src 'https://our.sonarqube.instance/some-checkstyle-ruleset'
    dest buildDir
    header "authorization", "Basic " + (apiToken + ":").bytes.encodeBase64()
}
```

**Comment by NielsDoucet** [comment]
Thanks for the fast reply and work-around. Can confirm this solves our problem 👍

**Comment by NielsDoucet** [comment]
Is there an easy way to debug the request/response flow executed by this plugin btw? I tried running with the `--debug` flag, but it didn't give me any extra output.
It would probably have given me more insights into what was going wrong and as such a better bug report for you.

**Comment by michel-kraemer** [comment]
Yes, I was thinking about this too. I guess it could be useful to log sent and received headers (like `curl` does if you set the verbose flag). I'll try to include this in the next release.

**Comment by NicoWallmeier** [comment]
I have a similar problem with 5.0.5 - I'm trying to download an artifact from a Jenkins server, which is working fine with version 4.1.2... The server response is:

HTTP/1.1 403 Forbidden
Date: Tue, 03 May 2022 10:17:04 GMT
X-Content-Type-Options: nosniff
Set-Cookie: JSESSIONID.c3cc7daa=node01prq7u994kp0z1raqu4nmrkrdw1768.node0; Path=/; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: text/html;charset=utf-8
X-Hudson: 1.395
X-Jenkins: 2.319.3
X-Jenkins-Session: b370b28f
Content-Length: 811
Server: Jetty(9.4.43.v20210629)

<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fjob%2FR8.4_TelegramClientV4CE%2Fnode%3Dbuild-windows%2Cplatform%3Dce6%2FlastSuccessfulBuild%2Fartifact%2F*zip*%2FTelegramClientV4CE.zip'/><script>window.location.replace('/login?from=%2Fjob%2FR8.4_TelegramClientV4CE%2Fnode%3Dbuild-windows%2Cplatform%3Dce6%2FlastSuccessfulBuild%2Fartifact%2F*zip*%2FTelegramClientV4CE.zip');</script></head><body style='background-color:white; color:white;'>


Authentication required


</body></html>

**Comment by michel-kraemer** [comment]
@NicoWallmeier Did you try the workaround I posted above? It would be good to know if it works for you too. Thanks!

**Comment by NicoWallmeier** [comment]
@michel-kraemer: It is working after changing authorization to Authorization in your workaround...

**Comment by michel-kraemer** [comment]
@NicoWallmeier That's good to know. Thanks.

I'm working on a fix and will get back to you when it's ready.

**Comment by michel-kraemer** [comment]
I've just released gradle-download-task 5.1.0. Please update and use the new `preemptiveAuth` flag like so:

```gradle
task downloadFile(type: Download) {
    src 'https://our.sonarqube.instance/some-checkstyle-ruleset'
    dest buildDir
    username apiToken
    password ""
    preemptiveAuth true
}
```

**Comment by NicoWallmeier** [comment]
It is working fine for me now :)

**Comment by NielsDoucet** [comment]
I can also confirm this works. Thank you very much for the fast fix 👍
