### ISSUE TITLE
Add destDir parameter

### ISSUE THREAD

**Issue by mpnewcomb** [michel-kraemer/gradle-download-task#220]
The plugin can't tell when you want dest to be a directory if it does not exist and it will just rename the download to the file specified in dest. So, if you say dest = "${buildDir}/sub_dir" it will rename the file downloaded to sub_dir.

Right now, I do dest = { mkdir "${buildDir}/sub_dir" }

Add destDir so it is clear that you want to download the file to a directory (creating it as needed).

Thanks,
Michael

**Comment by michel-kraemer** [comment]
This is already possible. The most idiomatic way would be as follows:

```gradle
task downloadFile(type: Download) {
    src 'https://httpbin.org/image'
    dest layout.buildDirectory.dir("sub_dir")
}
```

Instead of `layout.buildDirectory`, you may also use `layout.projectDirectory`.
