### ISSUE TITLE
download task redirect url broken after 4.1.2 -> 5.1.0

### ISSUE THREAD

**Issue by JanGoerss** [michel-kraemer/gradle-download-task#222]
Issue

download task 
redirect url broken after 4.1.2 -> 5.1.0

gradle : 7.4.2

with error

de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ClientProtocolException: Service Unavailable

**Comment by michel-kraemer** [comment]
Can you please provide more information? What exactly is the problem? What are you expecting and what is happening instead? If possible, provide a sample build script to reproduce the issue. Thanks.

Note that `Service unavailable` typically means there's some kind of failure on the server side and that there's probably nothing you can do about it on the client side.

**Comment by michel-kraemer** [comment]
Thanks for the feedback!
