### ISSUE TITLE
download & upload  with auth ?

### ISSUE THREAD

**Issue by CMingTseng** [michel-kraemer/gradle-download-task#223]
Dear Sir

like  this post  https://stackoverflow.com/questions/12298178/maven-depend-on-assembled-zip

if i want upload with auth   a Encryption zip to  remote (like  Sonatype  Nexus)

and  

download  with auth  

How to do ?

THX

**Comment by michel-kraemer** [comment]
Note that with gradle-download-task, you can only *download* a file but not upload it. Assuming that your ZIP file has already been uploaded to your Nexus server, you just have to find the right URL and then configure a download task.

Example: Let's say you wanted to download the Vert.x documentation from Maven Central, which is also provided as a ZIP file. The URL to this ZIP file is https://repo1.maven.org/maven2/io/vertx/vertx-stack-docs/4.3.0/vertx-stack-docs-4.3.0-docs.zip. The download task would then be:

```gradle
task downloadFile(type: Download) {
    src 'https://repo1.maven.org/maven2/io/vertx/vertx-stack-docs/4.3.0/vertx-stack-docs-4.3.0-docs.zip'
    dest buildDir
}
```

If you need to authentication, please read the section on [authentication in the README](https://github.com/michel-kraemer/gradle-download-task#authentication). Basically, you just have to provide a `username` and `password`. That's all.

Let me know, if this helps and close the issue if it does. Thanks!

**Comment by CMingTseng** [comment]
Dear Sir

thx

i can download 

now  i will try unzip 

THX

**Comment by michel-kraemer** [comment]
Great! You may want to have a look at the following example for this:
https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/groovy/unzip/build.gradle

**Comment by CMingTseng** [comment]
> Great! You may want to have a look at the following example for this: https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/groovy/unzip/build.gradle
Dear Sir

thx ,your demo !!

now  i have other problem .

i ref your demo  

https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/groovy/unzip/build.gradle

& 

https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/groovy/lazy-src-and-dest/build.gradle

 to create  a demo 

https://github.com/CMingTseng/gradle-download-task_qa/blob/master/extra.gradle

https://github.com/CMingTseng/gradle-download-task_qa/blob/491059d841419a836feb2bbeb42ec07784cd98df/build.gradle#L2

can  teach me how get extra  input paras ?

THX

**Comment by michel-kraemer** [comment]
This question does not seem to be related to gradle-download-task anymore. I would recommend to ask your question on the Gradle [discussion board](https://discuss.gradle.org/).
