### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by OnClickListener2048** [michel-kraemer/gradle-download-task#224]
* What went wrong:
Execution failed for task ':app:copyWords'.
> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by michel-kraemer** [comment]
Can you please provide more information? What exactly is the problem? What are you expecting and what is happening instead? If possible, provide a sample build script to reproduce the issue. Thanks.
