### ISSUE TITLE
Unable to download files

### ISSUE THREAD

**Issue by sankalpverma** [michel-kraemer/gradle-download-task#229]
**Describe the bug**

A clear and concise description of what the bug is. What did you expect to happen and what happened instead?

**Sample build script**

If possible, provide a sample build script to reproduce the issue.

plugins {
    id 'java'
    id 'biz.aQute.bnd.builder' version '4.1.0'
    id 'net.wasdev.wlp.gradle.plugins.Liberty' version "$libertyGradlePluginVersion"
    id 'de.undercouch.download' version '4.0.4'
}

apply plugin: 'de.undercouch.download'

task downloadFile(type: Download) {
    src 'https://github.com/michel-kraemer/gradle-download-task/archive/refs/tags/5.1.0.zip'
    dest "$buildDir"
    overwrite true
}

I can see above task in the gradle logs getting executed -

2022-06-10T00:21:17.041+0530 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Realize task :com.ibm.zosconnect:downloadFile' started
2022-06-10T00:21:17.042+0530 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Realize task :com.ibm.zosconnect:downloadFile'
2022-06-10T00:21:17.042+0530 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Realize task :com.ibm.zosconnect:downloadFile' completed

but actual file is not getting downloaded anywhere.
any suggestions ?

**Comment by michel-kraemer** [comment]
Have you tried upgrading to the latest version 5.1.0 of gradle-download-task already?

**Comment by sankalpverma** [comment]
yes I have already tried 5.1.0.
task running successfully but not downloading actual file.

**Comment by michel-kraemer** [comment]
Sorry for my late reply. I was out of office.

Could it be that you're running into the same issue as in https://github.com/michel-kraemer/gradle-download-task/issues/217? Are you using a Mac M1 with OpenJDK AWS Corretto 1.8 aarch64? If so, what do you get if you try 5.1.0 with `gradle -d` to get debug output? If you like you can send me the debug output via email instead of posting it here publicly.

**Comment by sankalpverma** [comment]
It is indeed, its same issue :)
Now I started running the same code on intel mac and works perfectly fine. I think I am good for now.


I really want to thank you for your time @michel-kraemer . Really appreciate it.
