### ISSUE TITLE
Allow customization of SSL client verification

### ISSUE THREAD

**Issue by punya** [michel-kraemer/gradle-download-task#23]
It would be really useful to have one or more of the following for dealing with non-public certificates (which often come up in corporate environments):
* specifying a trust store
* turning off host verification

**Comment by michel-kraemer** [comment]
Very good idea! I'm really busy at the moment with other projects so it might take a while until I can implement this feature. If you need it faster, then don't hesitate to send a pull request. It would be very much appreciated :-) Thanks.
