### ISSUE TITLE
Improve log output for parallel downloads

### ISSUE THREAD

**Issue by sschuberth** [michel-kraemer/gradle-download-task#243]
With parallel downloads, it seems the log lists all (in may case > 3000) URLs at once as they are queued, but not when the actual download happens (as I don't assume all 3000 URLs are being downloaded from at the same time).

So, it would be nice if the log output would reflect which URLs are currently being downloaded from a time.

**Comment by michel-kraemer** [comment]
How are you executing the task? Are you on an interactive terminal (where you should get a progress bar for each file currently being downloaded) or are you running Gradle on some kind of CI server where you only see the log messages and no progress bar?

**Comment by sschuberth** [comment]
I'm using Git Bash for Windows, running in mintty as a terminal. But I also tried the new Windows Terminal app from Windows 11. In any case running [this task](https://github.com/oss-review-toolkit/ort/blob/2255268ced6d49777e9eff2acbfdabbb1b8859c5/utils/spdx/build.gradle.kts#L93-L99) looks like:

```
C:\Users\Sebastian\Development\GitHub\oss-review-toolkit\ort>gradlew.bat importScanCodeLicenseTexts
Configuration on demand is an incubating feature.

> Configure project :
Building ORT version 2255268ced-dirty.
Fetching directory listing from https://api.github.com/repos/nexB/scancode-toolkit/git/trees/develop...

> Task :utils:spdx-utils:importScanCodeLicenseTexts
Download https://raw.githubusercontent.com/nexB/scancode-toolkit/develop/src/licensedcode/data/licenses/389-exception.LICENSE
Download https://raw.githubusercontent.com/nexB/scancode-toolkit/develop/src/licensedcode/data/licenses/389-exception.yml
<thousands of more URLs are printed to the console at once>
```

**Comment by michel-kraemer** [comment]
Please test the new version 5.1.3

**Comment by sschuberth** [comment]
> Please test the new version 5.1.3

That seems to do the trick, thanks!
