### ISSUE TITLE
Automatically add file to gitignore

### ISSUE THREAD

**Issue by almogtavor** [michel-kraemer/gradle-download-task#254]
**Is your feature request related to a problem? Please describe.**

When using this plugin for downloading .exe files (like helm.exe), it is common to add them to `.gitignore` for every project & file that it downloads.

**Describe the solution you'd like**

I think it is pretty reasonable to check if there is a `.gitignore` file in the same hierarchy of the `build.gradle` that declared the download. If there is and if the user had specified `addToGitIgnore = true`, add the file destination + file name as a new line in the `.gitignore`.

**Comment by michel-kraemer** [comment]
Interesting request, but this is definitely not a feature that should be part of gradle-download-task. You can easily create a separate task that depends on your download task and (if the download task was successfull) appends a line to your `.gitignore` file. Simply use one of the many convenience methods Groovy provides to append lines to files.

Having said that, if you know what you are going to download, why don't you add the entry to `.gitignore` right from the beginning?

I'm closing this as "won't fix".
