### ISSUE TITLE
Download a list of files with rename

### ISSUE THREAD

**Issue by marceloverdijk** [michel-kraemer/gradle-download-task#256]
Looking at the example to download a list of files:

```
task downloadMultipleFiles(type: Download) {
    src([
        'http://www.example.com/index.html',
        'http://www.example.com/test.html'
    ])
    dest buildDir
}
```

would it be possible to specify an alternative name for each file?
and also to have a different destination folder per file?

Goal:
Downloading multiple images in various dimensions which should go into a separate destination folder for each dimension.
Like `/img/16x16/apple.png`, `/img/16x16/strawberry.png`, `/img/32x32/apple.png`, `/img/64x64/strawberry.png`, `/img/128x128/apple.png`, `/img/128x128/strawberry.png`
where there source is like `http://..../apple16.png`, `http://..../apple32.png` etc.

In above case I have the 2 fruits `apple` and `strawberry` and the dimensions `16`, `32`, `64` ,`128` and basically want to download this to specific folder structure.

**Comment by michel-kraemer** [comment]
Please have a look at the following example and let me know what is missing:
https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/groovy/multiple-files-rename/build.gradle

I suppose you also want to specify a different target path for each file and not only a different filename, right?

**Comment by marceloverdijk** [comment]
Hi Michel, thx for your swift reply.

Yes indeed, I also would like to specify a different target path..

I tried something the path to the url mapping like:

```
ext.urls = [
    'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD': 'foo/config.guess',
    'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD': 'bar/config.sub'
]

task downloadFiles(type: Download) {
    src urls.keySet()
    dest buildDir
    eachFile { f ->
        f.name = urls[f.sourceURL.toString()]
    }
}

```

but that gives a `java.nio.file.NoSuchFileException`.

**Comment by andrewparmet** [comment]
I'm running into this as well: https://github.com/andrewparmet/buf-publisher/pull/1/checks

Here's my config:
```kotlin
fun versionsToPublish(): List<Version> =
    listOf(
        "1.0.0",
        "1.1.0",
        "1.1.1",
        "1.2.0",
        "1.2.1",
        "1.3.0",
        "1.3.1",
        "1.4.0",
        "1.5.0",
        "1.6.0",
        "1.7.0",
        "1.8.0"
    ).flatMap { version ->
        listOf(Os.MAC, Os.WINDOWS, Os.LINUX).flatMap { os ->
            os.architectures.map { arch ->
                Version(version, os, arch)
            }
        }
    }

tasks.register<Download>("downloadBinaries") {
    val urls =
        versionsToPublish().associate {
            "https://github.com/bufbuild/buf/releases/download/v${it.version}/${it.fileName}" to it.version
        }

    src(urls.keys)

    eachFile {
        name = "${urls[sourceURL.toString()]}/$name"
    }

    onlyIfModified(true)

    dest("$buildDir/buf")
}
```

**Comment by andrewparmet** [comment]
Oddly enough if I allow the task to fail first then a subsequent Gradle invocation succeeds:

E.g. my CI config:

```yaml
      - name: Download binaries
        continue-on-error: true
        uses: gradle/gradle-build-action@v2
        with:
          arguments: downloadBinaries

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal build --info
```

**Comment by michel-kraemer** [comment]
The `name` property works similar to that of the built-in `Copy` task (https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html and https://docs.gradle.org/current/javadoc/org/gradle/api/file/FileCopyDetails.html). You can only change the name of the destination file but not the path. The `Copy` task offers a `relativePath` property. I will add something similar to gradle-download-task. Please stay tuned...

**Comment by michel-kraemer** [comment]
I've just added the properties `path` and `relativePath`. The `eachFile` action now behaves similar to that of the `Copy` task. You can even specify a relative directory in the `name` property and it will work (e.g. `name = "foo/test.txt"`).

I will release 5.3.0 soon but I want to think a little bit more about how to handle duplicate files (maybe with [DuplicatesStrategy](https://docs.gradle.org/current/javadoc/org/gradle/api/file/DuplicatesStrategy.html)?). I'll keep you posted.

**Comment by michel-kraemer** [comment]
gradle-download-task 5.3.0 has just been released. Have fun! Let me know if there is anything else missing. Thanks!

**Comment by marceloverdijk** [comment]
Thx @michel-kraemer !!
