### ISSUE TITLE
Could not find method src()  on extension 'download'

### ISSUE THREAD

**Issue by CMingTseng** [michel-kraemer/gradle-download-task#257]
Dear Sir

at 2022/5  i ask 

https://github.com/michel-kraemer/gradle-download-task/issues/223

after sometime  i pass 

i can   download  file and then unzip it 

i ref : https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/groovy/unzip/build.gradle & https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/groovy/lazy-src-and-dest/build.gradle

def src_path = "here is src file path"
                File zip_file = new File(" here is  download finish  zip file name with path")
                download {
                    src src_path
                    dest zip_file
                    overwrite true
                }
                copy {
                    from zipTree(zip_file)
                    into buildDir
                }
                zip_file.delete()

but now  the gradle can not work !!

it show  lost  src method 

can help fix it ?

THX

**Comment by michel-kraemer** [comment]
In the latest version, you have to replace `download` with `download.run`. See the [README](https://github.com/michel-kraemer/gradle-download-task#usage) for more information.

Let me know if this helps and close the issue if it does. Thanks.

**Comment by CMingTseng** [comment]
> In the latest version, you have to replace `download` with `download.run`. See the [README](https://github.com/michel-kraemer/gradle-download-task#usage) for more information.
> 
> Let me know if this helps and close the issue if it does. Thanks.
Dear Sir 

"download.run " is work 

THX
