### ISSUE TITLE
Cannot set the value of read-only property 'overwrite' on task 

### ISSUE THREAD

**Issue by miho** [michel-kraemer/gradle-download-task#27]
Hi,

i'm trying to set custom properties to prevent Gradle from downloading large files each time I compile the project.

```gradle
task downloadBoostHeaders(type: Download) {
    src 'http://deps.mihosoft.eu/boost/1.58.0/headers/boost.zip'
    dest "$projectDir/src/main/native/ext/headers/boost.zip"
    
    overwrite = false
}
```

Gradle 2.4 gives me the following error:

    Cannot set the value of read-only property 'overwrite' on task

**Comment by michel-kraemer** [comment]
Try

    overwrite false

instead of

    overwrite = false

This should do the trick.

Cheers,
Michel

**Comment by miho** [comment]
Works. Thanks!

**Comment by michel-kraemer** [comment]
By the way: see the `examples` directory for more samples:
https://github.com/michel-kraemer/gradle-download-task/tree/master/examples

Let me know if you have any more questions.

Cheers,
Michel
