### ISSUE TITLE
Does plugin support to download file from local a relative file?

### ISSUE THREAD

**Issue by simonjhy** [michel-kraemer/gradle-download-task#274]
**Describe the bug**
does this download plugin support to download file from a relative url?
A clear and concise description of what the bug is. What did you expect to happen and what happened instead?

**Sample build script**
downloadLocalFile {
	dest new File(buildDir, "bundle.tar.gz")
	onlyIfModified true
	src "file:src/gradleTest/relativeUrl/bundle.zip"
}

If possible, provide a sample build script to reproduce the issue.

**Comment by michel-kraemer** [comment]
Yes, it does. Just use the following notation:

```gradle
src file("src/gradleTest/relativeUrl/bundle.zip").toURI().toURL()
```

**Comment by simonjhy** [comment]
Can i just put "file:src/gradleTest/relativeUrl/bundle.zip" not use "src file("src/gradleTest/relativeUrl/bundle.zip").toURI().toURL()" this type?

**Comment by michel-kraemer** [comment]
You have to pass a valid URI to `src`. `file:src/gradleTest/relativeUrl/bundle.zip` is not a valid URI. File URIs always have to be absolute. That's just how URIs work. Correct me if I'm wrong but I don't think you can get around the `file(...).toURI().toURL()` call.

**Comment by simonjhy** [comment]
if I set src file("src/gradleTest/relativeUrl/bundle.zip").toURI().toURL(), ,the download task will automaticaly to add current project path as a prefix? Where can I found that part code? Because we will invoke download task in our plugin, so we can not directly to set file("src/gradleTest/relativeUrl/bundle.zip").toURI().toURL() in a properties file.

**Comment by simonjhy** [comment]
it can directly use "src/gradleTest/relativeUrl/bundle.zip" to set src url when we use older version gradle download task. When I tried to upgrade to 5.0.0, it always try to find this in "/home/simon/.gradle/daemon/6.9.2/src/gradleTest/relativeUrl/bundle.zip"

**Comment by michel-kraemer** [comment]
`file()` is a built-in function from Gradle. It's an alias of `project.file()`. It should return a `File` object that is relative to the project directory. Alternatively, you can use `new File(projectDir, "src/gradleTest/relativeUrl/bundle.zip").toURI().toURL()`. This should get you the same result.

**Comment by michel-kraemer** [comment]
If you haven't worked with files in Gradle yet, this page might help you:
https://docs.gradle.org/current/userguide/working_with_files.html
