### ISSUE TITLE
HTTP status 302 FOUND

### ISSUE THREAD

**Issue by gingo** [michel-kraemer/gradle-download-task#28]
Im in trouble downloading file from Dropbox. There is HTTP 302 redirect to temporary link for file download. You can try it with this URL:

https://www.dropbox.com/s/hqibjpiiw5fayu8/aaa.txt?dl=1

My task:

```
task downloadFile << {
    download {
        src 'https://www.dropbox.com/s/hqibjpiiw5fayu8/aaa.txt?dl=1'
        dest '.'
    }
}
```

failes with exception and message:

"Could not download file"

**Comment by michel-kraemer** [comment]
I was able to download the file without problems by setting a correct value for `dest`:

```gradle
task downloadFile << {
    download {
        src 'https://www.dropbox.com/s/hqibjpiiw5fayu8/aaa.txt?dl=1'
        dest new File(buildDir, "aaa.txt")
    }
}
```

By the way, you may also write

```gradle
task downloadFile(type: Download) {
    src 'https://www.dropbox.com/s/hqibjpiiw5fayu8/aaa.txt?dl=1'
    dest new File(buildDir, "aaa.txt")
}
```

This is a bit shorter.

Please make sure you use the latest version of gradle-download-task. I tested it with 1.2, but I will release 2.0.0 today and it should definitely work. If not, please let me know.

Cheers,
Michel
