### ISSUE TITLE
Support progress bar when executing task via IntelliJ

### ISSUE THREAD

**Issue by alexstaeding** [michel-kraemer/gradle-download-task#288]
**Is your feature request related to a problem? Please describe.**

When executing this task from a terminal, the progress bar works as described. However, when executing this task from IntelliJ for example, the only output that is shown looks like this. There is no visible progress bar at all.

In this example, I double-click on `downloadFoo` in the right menu, which executes the task.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/24614463/215288024-4482770a-1ba1-43f2-bcd1-63c8a8d5101b.png">

```
> Task :downloadFoo
Download https://speed.hetzner.de/1GB.bin
20:48:23: Execution finished 'downloadFoo'.
```

**Describe the solution you'd like**

The progress bar should also be visible when executing via the Gradle task menu in IntelliJ

**Comment by michel-kraemer** [comment]
The build output window in IntelliJ is not a terminal, so Gradle automatically disables all rich (or interactive) output. See the following section for more information:
https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_customizing_log_format

In other words, it is impossible to display an interactive progress bar in this window. By the way, Gradle also does not display the build progress there (like it does on the terminal), nor does it display any progress when it downloads artifacts.

If you want to see progress, I recommend using the built-in terminal. It works perfectly there.

I'm closing this issue as it "won't fix". Sorry.
