### ISSUE TITLE
How to send Post Body Parameter (data)

### ISSUE THREAD

**Issue by M-Abughali** [michel-kraemer/gradle-download-task#303]
we have a post url request which require body data to be sent , but unfortunately we can't find any function/keyword supports us to achieve data , is there any methodology or advices for us ?

Thanks in advance

**Comment by michel-kraemer** [comment]
At the moment, gradle-download-task only supports the HTTP GET method, but what you're proposing sounds like an interesting idea. Can you please tell me more about your use case, so I can decide whether this feature would be useful for other users as well? What kind of data are you trying to send? Form data? Are you really downloading data or are you just trying to send (i.e. upload) data?

**Comment by M-Abughali** [comment]
Hey dear @michel-kraemer 
currently we are using 3rd library which provide us the translation string files and to defined the files format (xml, json , etc ) we need to send POST request with Body attribute for defined the files format (     --data '
{
     "format": "android_sdk"
}
)

**Comment by michel-kraemer** [comment]
I've just publish version 5.4.0. Please use the `method` and `body` properties (see ‘Advanced’ section in README).

**Comment by M-Abughali** [comment]
@michel-kraemer thanks a lot
