### ISSUE TITLE
Download plugin doesn't encoded files

### ISSUE THREAD

**Issue by bric3** [michel-kraemer/gradle-download-task#337]
**Describe the bug**

When downloading multiple files, the destination directory has to be a folder. And when files have spaces or other characters, they need to be URI encoded as the plugin don't URI encode them, e.g. replacing spaces by `%20`.

```text
https://my-url.to/Someone's document.docx
```

However the files stored on disk are not decoded and are stored with the file name encoded.

```text
Someone's%20document.docx
```

Also the server which I do not own, does not hint at the file name :

```
HTTP/2 200 
last-modified: Sun, 03 Jun 2012 20:05:14 GMT
accept-ranges: bytes
content-length: 11752
date: Wed, 21 Jun 2023 13:51:29 GMT
server: Apache

<Payload>
```

I believe the issue comes from the fact the plugin is using the string after the last `/`, however as it is required to URI encode the string, the value is somewhat wrong.

This could be solved by an option that when toggled on could encode the source URI, but have the original value to compute the output file name for each download.

**Sample build script**

Since the server is not available on Internet, I'm just dropping the code, but cannot be tested.

```
// list acquired by other means
var filenames = listOf(
   "[2022-01-10] Someone's document.docx",
   "[2022-02-21] Yet another document.rtf",
)

project.download.run {
    src(fileNames.map { "https://my-url.internal/${it}".encodeURI() })
    dest("${project.buildDir}/docs")
    compress(true)
    tempAndMove(true)
    onlyIfNewer(true)
    onlyIfModified(true)
}
```

This will results in files :
```text
%5B2022-01-10%5D%20Someone's%20document.docx
%5B2022-02-21%5D%20Yet%20another%20document.rtf
```

**Comment by michel-kraemer** [comment]
Did you have a look at the `eachFile` property?

```groovy
eachFile { f ->
    f.name = URLDecoder.decode(f.name, "UTF-8")
}
```

**Comment by bric3** [comment]
@michel-kraemer Ah thank you I completely missed that property when reading the doc. For other readers, the `setName` etc, is applied on the receiver of the functon, i.e. `this`.

```kotlin
eachFile {
    name = URLDecoder.decode(name, "UTF-8")
}
```

I guess this closes the issue.

That said it would be practical to have this backed in the plugin. As encoding URLs is not straightforward in the JDK ; `URLEncode` for example is misleading as it applies to URL's query params not on path segment, and `URI` constructor doesn't allow to pass non encoded `url` string. That's why Spring or Guava have their own utils method for that.
