### ISSUE TITLE
mirrors

### ISSUE THREAD

**Issue by guai** [michel-kraemer/gradle-download-task#36]
Hi
Pls add support for multiple urls for a single file
So first successful download should stop subsequent requests

**Comment by michel-kraemer** [comment]
You can easily implement such a functionality yourself. I just uploaded an example demonstrating how to use mirror servers:

https://github.com/michel-kraemer/gradle-download-task/blob/e15413897e3e57dc29d598fb4b107355cb405034/examples/mirrors.gradle

I hope this solves your problem. Pull requests are always more than welcome :-)

Cheers,
Michel
