### ISSUE TITLE
Unable to pass strings with tokens

### ISSUE THREAD

**Issue by javydreamercsw** [michel-kraemer/gradle-download-task#40]
I would like to send a url that varies at run time. For example: 
"http://download.oracle.com/otn-pub/java/jdk/${minor}u${update}-b${build}/jre-${minor}u${update}-windows-x64.${extension}"

On my code it translates correctly to:
http://download.oracle.com/otn-pub/java/jdk/8u74-b02/jre-8u74-windows-x64.exe

But gives out the following error:

Cannot set readonly property: src for class: de.undercouch.gradle.tasks.download.DownloadAction

Using the hard coded URL works perfectly.

**Comment by michel-kraemer** [comment]
The `src` property can be a Groovy closure that is called when executing the `Download` task.

This should solve your problem, but I'll keep this issue open because this reminded me that I need to update the docs and provide an example for this use case. Thanks!

**Comment by javydreamercsw** [comment]
Could you document such example here? I have no groovy experience so I have
no idea what are you talking about.

**Comment by javydreamercsw** [comment]
The issue was that I was doing src = "http..." and it should have been src "http..."

Silly me!

**Comment by michel-kraemer** [comment]
Oh really? Cool. Didn't notice that myself.

So, the issue is resolved I guess?

**Comment by javydreamercsw** [comment]
Yes, that solved the issue for me. It worked fine after that simple change.
