### ISSUE TITLE
Not work when combine with apply from feature

### ISSUE THREAD

**Issue by abccbaandy** [michel-kraemer/gradle-download-task#416]
**Describe the bug**
I want use a `common.gradle` to share some config to others.
The repo need auth so `apply from url` way not work.
I find this plugin, it work well alone, but when combine with apply from, gradle just keep give me the error like:
````
A problem occurred evaluating root project 'XXX'.
> Could not read script 'C:\XXXX\common.gradle' as it does not exist.
````
But it should do downloadFile first.

**Sample build script**

````groovy
tasks.register('downloadFile', Download) {
    src 'https://XXXXXXX/common.gradle'
    dest layout.projectDirectory
    username 'XXXX'
    password 'XXXX'
}

tasks.every {
    if (it.name != 'downloadFile') {
        it.dependsOn downloadFile
    }
}

apply from: 'common.gradle'
````

workaround:
I have to comment out the `apply from` to trigger the task, but it seems weird

**Comment by michel-kraemer** [comment]
`apply from` is evaluated during Gradle's configuration phase, whereas the task is executed later in the execution phase. This means that even though you put `apply from` after the task definition in your `build.gradle`, it will actually be evaluated first. Please see the Gradle documentation for more information about build phases:
https://docs.gradle.org/current/userguide/build_lifecycle.html

Note that this is not related to gradle-download-task but Gradle itself. I will close this issue. If you need further help, I recommend posting the question in the Gradle discussion board:
https://discuss.gradle.org/
