### ISSUE TITLE
Create Directory if multiple Files are downloaded

### ISSUE THREAD

**Issue by fwilhe** [michel-kraemer/gradle-download-task#44]
This is my `build.gradle` (the example is fully self contained and I tested it with gradle 2.12)

```
buildscript {
    repositories {
        jcenter()
    }
}

plugins {
    id "de.undercouch.download" version "2.1.0"
}

repositories {
    jcenter()
}

import de.undercouch.gradle.tasks.download.Download

task download(type: Download) {
    src([
        'http://central.maven.org/maven2/org/citationstyles/styles/1.0/styles-1.0.jar',
        'http://central.maven.org/maven2/org/eclipse/jetty/jetty-server/9.1.3.v20140225/jetty-server-9.1.3.v20140225-javadoc.jar'
    ])
    dest 'vendor'
}

defaultTasks 'download'
```

I would expect this build to create a `vendor` directory, it it does not exist.

What happens is

```
:download FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':download'.
> If multiple sources are provided the destination has to be a directory.
```

Our workaround is to create the directory in `doFirst` of the task.

```
    doFirst {
        // The plug-in does not create the output directory by itself.
        // So, we have to do it before the download starts.
        dest.mkdirs()
    }
```

Would it be possible to implement this in the plugin? I think that in the case of more then one source-files, it is clear that `dest` can not be a file name, but rather must be a directory.

**Comment by michel-kraemer** [comment]
Yes. That's a good idea. I will implement it.

**Comment by fwilhe** [comment]
Nice, thank you very much for fixing that so quickly :+1: 

I would appreciate a new release containing this fix, in case that's not a big deal.

**Comment by michel-kraemer** [comment]
Yes, I'm working on a couple of other issues. I will release a new version when the other issues are fixed. Probably this weekend.

**Comment by fwilhe** [comment]
We're getting close to the release of our project, therefore a release of gradle-download-task in the near future with this fix included would be beneficial for us.

**Comment by michel-kraemer** [comment]
I uploaded a snapshot (3.0.0-SNAPSHOT):
https://oss.sonatype.org/content/repositories/snapshots/de/undercouch/gradle-download-task/3.0.0-SNAPSHOT/

Please test it and if it works I can release the new version 3.0.0. Thanks for your support.

**Comment by fwilhe** [comment]
Can confirm that the issue is solved with this snapshot. Thanks!

**Comment by michel-kraemer** [comment]
Thanks for testing! I'll release the new version today.
