### ISSUE TITLE
Gradle HTTPS/SSL Issue

### ISSUE THREAD

**Issue by scottdermott** [michel-kraemer/gradle-download-task#48]
:downloadZipFile'.
> Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory

Trying do download anything http or https results in this error

Using Gradle 2.10

**Comment by MarinKacaj** [comment]
I have the same problem.
Gradle 2.1.2

**Comment by scottdermott** [comment]
I think the issue is caused by JDK Version. I am using 1.79

**Comment by MarinKacaj** [comment]
I tried adding this to the dependencies:
`compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.4.1'`

**Comment by michel-kraemer** [comment]
Interesting. I haven't had this problem before. @scottdermott please use the workaround from @MarinKacaj for the time being. I'll look into the issue and try to fix it in the meantime.

**Comment by michel-kraemer** [comment]
Just to be on the safe side: can you send me a minimum example build.gradle demonstrating the error, so I can reproduce it? Thanks!

**Comment by MarinKacaj** [comment]
[build.zip](https://github.com/michel-kraemer/gradle-download-task/files/327159/build.zip)
This is the app module level build.gradle.
I'm using:
* Android Studio 2.1.2.
* JRE: 1.8.0_65-b17 amd64
* Windows 10
Hope this helps.
P.S.: Inside build.gradle replace "whatever" as appropriate with your test URLs, names, etc.

**Comment by michel-kraemer** [comment]
Thanks for the build file. However, it's not a minimal example. It's a rather complex one. I wasn't able to get it running. Can you try to reproduce the error without all the Android stuff? Thanks for your support.

**Comment by vanniktech** [comment]
Getting the same here what are you missing for fixing this?

**Comment by michel-kraemer** [comment]
It would be perfect if I could reproduce it. It works in all of my build files. If I can't reproduce it I can't fix it, unfortunately. :-/

**Comment by vanniktech** [comment]
Hmm my problem was that I declared everything in a subproject. When I moved everything to the root build.gradle file everything works now. Weird :/

**Comment by scottdermott** [comment]
I can confirm also by moving download tasks to the root build.gradle this resolves the issue.
It appears that if the Android gradle plugin is applied within the same build.gradle 
`apply plugin: 'com.android.application'`
The issue is present

**Comment by michel-kraemer** [comment]
Interesting. Thanks for posting your solution (i.e. workaround). Let me know if there is anything I can do in gradle-download-task to mitigate this issue. But I suspect it has probably something to do with the way how Gradle manages plugin classpaths.

**Comment by dolmens** [comment]
Yes, By moving the dependency 'de.undercouch:gradle-download-task:3.1.1' to root build.gradle solve this problem.

**Comment by linsea** [comment]
@MarinKacaj I met the same problem, have you fixed it?
@michel-kraemer moving dependency to the top level build.gradle did not fix my problem. I have a `buildSrc` project,  but it does not inculde `org.apache.httpcomponents` module, I want to figure out the classpath of the gradle build, in order to see which versions of the http components conficts, but not found a way.

**Comment by michel-kraemer** [comment]
Please follow #75. I think it's the same issue. I'm trying to reproduce it and find a solution. I'll post updates in the other thread as this one is already closed.

**Comment by PashaTurok** [comment]
**$java -version**
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**$ gradle -v**

Gradle 6.5.1

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.9.0-6-amd64 amd64

**$ cat build.gradle** 
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.1"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**$ gradle --stacktrace**
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoClassDefFoundError: Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory
        at org.gradle.internal.resource.transport.http.HttpClientConfigurer.configureSslSocketConnectionFactory(HttpClientConfigurer.java:122)
        at org.gradle.internal.resource.transport.http.HttpClientConfigurer.configure(HttpClientConfigurer.java:107)
        at org.gradle.internal.resource.transport.http.HttpClientHelper.getClient(HttpClientHelper.java:195)
        at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:141)

**Could anyone help me to solve this problem?**

**Comment by michel-kraemer** [comment]
@PashaTurok Please open a new issue instead of commenting on an old one. Please also include the version of gradle-download-task you are using. Thanks.

**Comment by PashaTurok** [comment]
@michel-kraemer Thank you for your answer. I will open a new issue, but could you say how to check the version of gradle-download-task?

**Comment by PashaTurok** [comment]
@michel-kraemer I am sorry, I thought this is gradle github...
