### ISSUE TITLE
No test coverage for gzip compression feature

### ISSUE THREAD

**Issue by jberkel** [michel-kraemer/gradle-download-task#51]
I tried to add this while working on #43, but gave up because the version of Jetty used was quite old which made it difficult to find good documentation. Any reason we can't use Jetty 9.X?

**Comment by michel-kraemer** [comment]
AFAIK Jetty 9.x requires Java 1.8 or higher. At the moment gradle-download-task is still compatible with Java 1.6. I know that the tests could be run under 1.8, but I prefer to use 1.6 for both, compiling and testing - just to be consistent.

What exactly could you not find in the Jetty documentation?

**Comment by jberkel** [comment]
I was trying to set up a gzip handler, without requiring a full blown web context / web.xml. This is easy to do with Servlet API 3.0+, but a bit trickier with the older version. I'm sure it's possible somehow, just did not want to spend more time on it.

**Comment by michel-kraemer** [comment]
There already is a test for the GZIP feature:
https://github.com/michel-kraemer/gradle-download-task/blob/4ee0689/src/test/java/de/undercouch/gradle/tasks/download/CompressionTest.java

I stepped through the code and noticed that the Apache HttpClient transparently handles compression. So the code in the `performDownload` method was actually dead code.

**Comment by jberkel** [comment]
ah, excellent. deleting code is even better!
