### ISSUE TITLE
how to use this plugin to download all dependencies??

### ISSUE THREAD

**Issue by snowdream** [michel-kraemer/gradle-download-task#52]
how to use this plugin to download all dependencies??

**Comment by michel-kraemer** [comment]
I suppose you'd like to download the dependencies specified in a `build.gradle`? These dependencies are downloaded by Gradle automatically. Gradle even shows a progress bar while downloading so there is nothing this plugin can add.

If you want to copy all downloaded dependencies to a certain folder or something like this please read the following StackOverflow thread:
http://stackoverflow.com/questions/21814652/how-to-download-dependencies-in-gradle

I hope this helps. Please let me know if you have any further questions.

**Comment by snowdream** [comment]
i have to use gradle behind proxy.
and i met this error:

https://github.com/snowdream/SnowdreamFramework/issues/27

gradle-download-task has the feature: acceptAnyCertificate, but  Gradle has not.

**Comment by michel-kraemer** [comment]
The correct way is to import the unknown certificate into your keystore:
http://serviceorientedarchitect.com/using-gradle-wrapper-behind-a-proxy-server-with-self-signed-ssl-certificates/

gradle-download-task is not able to download dependencies specified in the `build.gradle`. In addition it's not possible to make Gradle to not try to download them itself. You could of course try to figure out the URLs of all your dependencies and move them from the `dependencies` block in your `build.gradle` to a separate download task, but then you will need to find a way to add the downloaded files as dependencies to your project again. I don't think this is possible (or at least very complex). I guess importing the certificate is much easier.

**Comment by snowdream** [comment]
keytool -importcert -alias cacerts -keystore "C:\Program Files\Java\jre1.8.0_66\lib\security\cacerts" -file CA.crt -trustcacerts

**Comment by Xgamefactory** [comment]
please provide a working example for lates gradle and android studio
