### ISSUE TITLE
Please support other protocols than Http

### ISSUE THREAD

**Issue by tomzi8571** [michel-kraemer/gradle-download-task#60]
In our project we would need either download from a windows share, eg \files\bigFiles\test.zip or from an sftp host

**Comment by michel-kraemer** [comment]
Very interesting idea. Thanks!

I don't have time to implement this feature at the moment, but I'll keep this request open, so I can probably implement it later this year. Pull requests are very welcome by the way.

Cheers,
Michel

**Comment by koppor** [comment]
It was possible with version 1.2

**Comment by michel-kraemer** [comment]
@koppor Thanks to @gamerson and #70 the current snapshot supports the file protocol, so it should be possible to download from Windows shares again. I haven't tried it yet though, so I'd be happy if someone could confirm.
