### ISSUE TITLE
Handle *.domain when checking SSL certificates.

### ISSUE THREAD

**Issue by Dubrzr** [michel-kraemer/gradle-download-task#61]
When downloading from Github releases I had the following error:

`javax.net.ssl.SSLPeerUnverifiedException: Host name 'github-cloud.s3.amazonaws.com' does not match the certificate subject provided by the peer (CN=*.s3.amazonaws.com, O=Amazon.com Inc., L=Seattle, ST=Washington, C=US)`

But github-cloud.s3.amazonaws.com match *.s3.amazonaws.com! So this should not produce the error.

**Comment by michel-kraemer** [comment]
Please see the following issue #56. The bug will be fixed with the next version of gradle-download-task, but the other thread includes a workaround. Hope this helps. Let me know if the problem persists.
