### ISSUE TITLE
org/gradle/logging/ProgressLogger has moved in Gradle 2.14

### ISSUE THREAD

**Issue by gamma** [michel-kraemer/gradle-download-task#64]
The Class org/gradle/logging/ProgressLogger has been moved to an internal package in Gradle Version 2.14. This is why the plugin fails when downloading a file.

**Comment by gamma** [comment]
Looks like a caching problem on our side. Sorry.

**Comment by shadowQ5** [comment]
what is the resolution for this one?

**Comment by gamma** [comment]
I think we used an outdated or not compatible version of the plugin.

**Comment by michel-kraemer** [comment]
Yes, this is usually the problem. Just update the plugin and the issue should go away.
