### ISSUE TITLE
SSLException when downloading file from github

### ISSUE THREAD

**Issue by bondyk** [michel-kraemer/gradle-download-task#65]
Hi,

Task fails to download file from github (url: https://github.com/softlayer/terraform-provider-softlayer/releases/download/v1.2.0/terraform-provider-softlayer_linux_amd64). 
Probably it's related to the [issue in Apache's  HttpClient ](https://issues.apache.org/jira/browse/HTTPCLIENT-1613) but I'm not sure.

See [logs](https://github.com/michel-kraemer/gradle-download-task/files/559071/download_error.txt)

**Comment by michel-kraemer** [comment]
The Apache issue has long been fixed. We're using the latest version of Apache HttpClient in gradle-download-task. Which version of gradle-download-task are you using?

**Comment by bondyk** [comment]
Version 3.1.1.
Then it's not the same issue but looks similar.

**Comment by michel-kraemer** [comment]
Ah, I see. I'm sorry for the confusion. This issue has been reported before and I already fixed it in master, but a new version has not been released yet. Please see the following comment for a temporary workaround:

https://github.com/michel-kraemer/gradle-download-task/issues/56#issuecomment-236349889

You can remove the workaround once the new version has been released. If you wish I can publish a minor patch tomorrow.

**Comment by michel-kraemer** [comment]
I just released version 3.1.2. It should fix the issue. Please test it and close the issue if it works. Thanks.

Cheers,
Michel

**Comment by bondyk** [comment]
Great! It works now! Thanks a lot!
