### ISSUE TITLE
File always downloads when any task is run, not when it's task is run

### ISSUE THREAD

**Issue by novaterata** [michel-kraemer/gradle-download-task#69]
I have a task with a download closure in it, and even if I run somthing as simple as

    gradle clean check

The file downloads even though the task it is configured in has nothing to do with clean or check.

**Comment by michel-kraemer** [comment]
Maybe the declaration of your task containing the download closure is wrong. Task definitions are executed during configuration phase. See the following link:

https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:adding_dependencies_to_tasks

> A task has both configuration and actions. When using the <<, you are simply using a shortcut to define an action. Code defined in the configuration section of your task will get executed during the configuration phase of the build regardless of what task was targeted.

Let me know if this solves your problem. If not, please upload a small `build.gradle` file demonstrating your problem, so I can have a look at it.

Cheers,
Michel

**Comment by novaterata** [comment]
It does, that makes sense. I just moved it into a Download task
