### ISSUE TITLE
Feature request/question: cache downloaded files globally, across builds

### ISSUE THREAD

**Issue by blendmaster** [michel-kraemer/gradle-download-task#73]
Hi, I've got a use case I think similar to #67, but not quite: 

My build requires an extra code generation utility, a static binary. Currently, I do:

```
    task downloadUtil(type: Download) {
        src 'http://example.com/utility'
        dest file("${project.buildDir}/utility")
        onlyIfNewer true
    }

    task mungeStuff(type: Exec) {
      commandLine("${project.buildDir}/utility","some","options")
    }
    mungeStuff.dependsOn downloadUtil
```

This works fine. However, if I run `gradle clean` for some reason, the build directory is cleaned out, and the tasks dutifully re-downloads the utility. It's a relatively large download, so this takes a while. In contrast, all the other maven dependencies of my project remain in my user-global `~/.gradle/caches` dir, and are not redownloaded after a clean. Similarly, my other projects (or git-worktree checkouts) that depend on the same utility end up downloading their own copies, but share the maven dependencies.

Is there a good way for this project to interact with `~/.gradle/caches` so that a download is cached globally across gradle runs? It's straightforward to change the `dest` in my example code to e.g. `${env.HOME}/.gradle/downloaded-stuff`, but I'm hoping for something less ad-hoc, especially wrt to different platforms. I looked around for a standard way to point to `~/.gradle` from inside a build script, but couldn't find anything.

**Comment by michel-kraemer** [comment]
As far as I know there is no standardised way to access `~/.gradle` from inside a build script. I'm even unsure if we could access it from inside the plugin. If you find something in the Gradle documentation please let me know.

Does somebody else know a solution?

**Comment by gesellix** [comment]
you can define your own "root" for the Gradle base dir, see https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_properties_and_system_properties
I guess the `GRADLE_USER_HOME` env variable is a good start.

**Comment by gesellix** [comment]
P.S. in fact, I used it in a Dockerized build environment to keep the Gradle caches in a custom Docker Volume.

**Comment by michel-kraemer** [comment]
@blendmaster This issue is more than two months old and we haven't heard back from you. I'll close it for the time being. Let us know if @gesellix's tips helped you or not and if there is anything else we can do for you. Feel free to reopen the issue if necessary.
