### ISSUE TITLE
No progress displayed?

### ISSUE THREAD

**Issue by karl0ss** [michel-kraemer/gradle-download-task#76]
I am trying to use this plugin in my gradle project...

I have added --

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'de.undercouch:gradle-download-task:3.2.0'
    }
}

apply plugin: 'de.undercouch.download

```
to my project then added --

```
import de.undercouch.gradle.tasks.download.Download

task downloadZipFile(type: Download) {
    src 'https://github.com/michel-kraemer/gradle-download-task/archive/1.0.zip'
    dest new File(buildDir, '1.0.zip')
}

task downloadAndUnzipFile(dependsOn: downloadZipFile, type: Copy) {
    from zipTree(downloadZipFile.dest)
    into buildDir
}

```

When i run ./gradlew downloadAndUnzipFile the task executes, and it downloads the file, but no progress is displayed? I thought this was the whole idea of this plugin, so I wonder what I'm doing wrong...hope someone can help?

Thanks

**Comment by karl0ss** [comment]
Just to update this, I am using windows and executing using MINGW64.

If I execute using gradlew.bat via CMD, it does show the progress..

**Comment by michel-kraemer** [comment]
This is probably something you should post on the Gradle forums. I'm not 100% sure if Gradle supports MINGW64 fully. In order to display the progress we access internal Gradle API (`org.gradle.internal.logging.progress.ProgressLoggerFactory`). If this class cannot handle MINGW64 we cannot do so either.

**Comment by karl0ss** [comment]
Ok, Thank you for letting me know.
