### ISSUE TITLE
Unable to download file due to SSLHandshakeException

### ISSUE THREAD

**Issue by bondyk** [michel-kraemer/gradle-download-task#78]
Unable to download file https://releases.hashicorp.com/terraform/0.8.7/terraform_0.8.7_linux_amd64.zip. Task fails with error javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake (see [log file](https://github.com/michel-kraemer/gradle-download-task/files/814913/download.txt))

Using the latest version of the plugin (3.2.0).

**Comment by michel-kraemer** [comment]
I created a small build file and tested it with Gradle 3.4. Downloading works for me. Here is my build file:

```gradle
plugins {
    id "de.undercouch.download" version "3.2.0"
}

task down(type: de.undercouch.gradle.tasks.download.Download) {
    src 'https://releases.hashicorp.com/terraform/0.8.7/terraform_0.8.7_linux_amd64.zip'
    dest buildDir
}
```

Let me know if you find any differences between my build file and yours that could lead to such an error. Maybe you're using a custom version of Apache HttpClient? Would it be possible to update it to the latest version?

**Comment by bondyk** [comment]
Here is my build file:
```
plugins {
	id "de.undercouch.download" version "3.2.0"
}
import de.undercouch.gradle.tasks.download.Download

def OS = 'linux'
def ARCH = 'amd64'
def TERRAFORM_VERSION = '0.8.7'

task downloadTerraformZip(type: Download) {
	src "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_${OS}_${ARCH}.zip"
	dest new File(buildDir, "terraform_${TERRAFORM_VERSION}_${OS}_${ARCH}.zip")
	onlyIfNewer true
}
```

Gradle version is 3.3 and I don't use any specific version of HttpClient, in logs found that gradle downloads httpclient:4.5.2.
Probably the only difference is java. I use ﻿"IBM SDK for Linux, Java Technology Edition, Version 8" so I assume the error is somewhere there.

**Comment by michel-kraemer** [comment]
Maybe your system is missing some certificates. Or you have to install the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files? The following StackOverflow thread lists some possible causes:

http://stackoverflow.com/questions/21245796/javax-net-ssl-sslhandshakeexception-remote-host-closed-connection-during-handsh

I hope this helps. I think we can close the issue here because it seems it's not related to gradle-download-task. What do you think?

**Comment by bondyk** [comment]
Thanks, I'll check that out.
Closing the issue.
