### ISSUE TITLE
Please upgrade Apache httpclient dependency to 4.5.3

### ISSUE THREAD

**Issue by apetres** [michel-kraemer/gradle-download-task#79]
Version [4.5.3](http://www.apache.org/dist/httpcomponents/httpclient/RELEASE_NOTES-4.5.x.txt) fixes a number of defects, and one of them caused an issue in our project. The issue disappeared after we included 'org.apache.httpcomponents:httpclient:4.5.3' into the classpath.

**Comment by michel-kraemer** [comment]
No problem. I updated the dependency and uploaded a new snapshot. If you wish you can try it as follows:

```gradle
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath 'de.undercouch:gradle-download-task:3.2.1-SNAPSHOT'
    }
}

apply plugin: 'de.undercouch.download'
```

Let me know if the snapshot solves your problem or not.
