### ISSUE TITLE
Is it possible to add a timeout if download is taking longer than expected?

### ISSUE THREAD

**Issue by anandbagmar** [michel-kraemer/gradle-download-task#80]
I am downloading a file as part of running my tests on (unfortunately) a very unreliable & slow internet connection. When such internet problem occurs, if my test is in the stage of download a particular file, it just gets stuck there indefinitely.

Is there a way an optional timeout value (in seconds) can be provided to the download command, that will abort the download if specified?

Thanks.

**Comment by michel-kraemer** [comment]
Very good idea! 👍

I implemented a new property called `timeout` which specifies the maximum number of milliseconds to wait until a connection is established or until the server returns data. I published the feature as 3.3.0-SNAPSHOT. Please let me know if this is what you expected so I can publish a new release. Thanks!

**Comment by anandbagmar** [comment]
Thanks @michel-kraemer . However, I was not able to get to this 3.3.0-SNAPSHOT. 

Looking at the changes, it seems that this timeout configuration will take care of cases where it takes a long time to establish the connection, or for data to start getting downloaded, right? 

If yes, I was actually thinking of a timeout value for the overall download process - say - download (including connection time / etc.) for my specified set of file(s) should complete within 60 sec, else, I should see a Timeout error.

**Comment by michel-kraemer** [comment]
Thanks for the clarification. I understand your use case, but I'd rather not add such a very specific functionality to gradle-download-task which is (more or less) a general-purpose plugin.
