### ISSUE TITLE
Support conditional requests based on ETag

### ISSUE THREAD

**Issue by ssoloff** [michel-kraemer/gradle-download-task#82]
The Download task currently supports conditional requests based on the `Last-Modified` response and `If-Modified-Since` request headers.  However, I've run into a use case where the server only provides an entity tag in the response.  (In this use case, the server generates the file dynamically, so it presumably cannot efficiently calculate a meaningful "last modified" time.)  As the file I'm downloading is > 250 MiB and rarely changes, not being able to prevent re-downloading the unmodified file is somewhat painful. 😞

At first, I thought I might be able to roll my own support for entity tags by using the `header` property to specify the appropriate `If-None-Match` header in the request.  However, I couldn't find a way to extract the `ETag` header from the initial response so I could cache it for later use.  Please advise if I somehow overlooked this feature.

Otherwise, would it be appropriate to add support for conditional requests based on the `ETag` response and `If-None-Match` request headers to the Download task?

**Comment by michel-kraemer** [comment]
> Otherwise, would it be appropriate to add support for conditional requests based on the ETag response and If-None-Match request headers to the Download task?

This is a very good proposal. I'd love to implement this. Any idea where the etag should be stored locally?

**Comment by ssoloff** [comment]
Thanks for the positive reception, @michel-kraemer!

> Any idea where the etag should be stored locally?

Heh, I was going to ask you, as I'm not familiar with the Gradle plugin conventions for storing temporary files.

In the past, I've used your task to store my downloads in `build/tmp/downloads`.  I don't know if `build/tmp` is idiomatic Gradle (I don't think I came up with that path on my own--I must have read about it or seen another project use it; maybe there's a public Gradle API that provides this path?).  So would `build/tmp/de.undercouch.download/<etag-cache-file>` work?

I'm perfectly content with the consequence that if I clean my build (i.e. deleting the `build` directory), I will have to redownload my files because the ETag cache has been blown away.

**Comment by michel-kraemer** [comment]
Thanks for pointing me to `build/tmp`. I investigated Gradle's source code and the API and found `Task.getTemporaryDir()`. This method in fact returns a new directory under `build/tmp` which is unique for the current task, but the documentation says "There are no guarantees that the contents of this directory will be kept beyond the execution of the task."

So, although at the moment it looks like the directory is actually kept, this isn't something we should rely on for future versions of Gradle.

I then looked at Gradle's own `ApplicationPlugin` and found out that they use default values such as `new File(project.getBuildDir(), "scripts")` which users can overwrite with a task property. The same is true for reporting plugins (e.g. JacocoPlugin) etc. I think this is the way to go for gradle-download-task too.

We could use `new File(project.getBuildDir(), "etags")`. Or maybe something more generic like `new File(project.getBuildDir(), "gradle-download-task")` What do you think?

**Comment by ssoloff** [comment]
Thanks for the heads-up on `Task.getTemporaryDir()`.

> We could use new File(project.getBuildDir(), "etags"). Or maybe something more generic like new File(project.getBuildDir(), "gradle-download-task") What do you think?

Yeah, it's hard to say which one is preferable.  Looking at the contents of `build` for several of my projects, I don't see a consistent naming pattern for immediate child folders.  One example I found that mixes a lot of different conventions follows:

```
classes    dependency-cache  distributions  instrumented-classes
jacoco     libs              publications   reports
resources  test-results      tmp
```

There seem to be "collections of things", like `classes`, `libs`, `reports`, etc.; "products" or "tasks", like `jacoco`; and "generic containers", like `dependency-cache` and `tmp`.

So I guess either of your proposed choices wouldn't be breaking any kind of convention that I haven't seen before.  I would think `build/gradle-download-task` is the safer choice as there's probably a small possibility that some other task author could decide `build/etags` would be a good choice for their own ETag caching mechanism.  I see the `build/jacoco` folder I mentioned above sort of setting a precedent in this regard (`build/jacoco` is apparently the location where the JaCoCo task stores the actual code coverage data [i.e. `*.exec` files] for use beyond the Gradle run in which it was generated).

I was thinking about a third possibility that lines up with the "collections of things" convention I noted above: something like `build/caches/gradle-download-task`.  I see that the Gradle [Build Cache](https://docs.gradle.org/current/userguide/build_cache.html) uses a similar naming convention, albeit it's stored under `~/.gradle`, as in `~/.gradle/caches/<something>`.  In a sense, gradle-download-task would then be trying to establish a convention for other task authors to cache inter-build data under `build/caches`, and that may be too pretentious. :smiley:

**Comment by michel-kraemer** [comment]
> I would think `build/gradle-download-task` is the safer choice

Yes, I think so too.

> I see the `build/jacoco` folder I mentioned above sort of setting a precedent in this regard

Nice catch!

So `build/gradle-download-task` it is.

I will implement this feature in the next couple of days. In the meantime you can use the following workaround:

```gradle
task downloadFile(type: Download) {
    def etagFile = new File(buildDir, 'etag.txt')
    def etag = etagFile.exists() ? etagFile.text : ''

    src 'http://example.org'
    dest new File(buildDir, 'file.txt')
    header 'If-None-Match', etag

    responseInterceptor { response, context ->
        def hdr = response.getFirstHeader('ETag')
        if (hdr) {
            etagFile.text = hdr.value
        }
    }
}
```

Execute this twice and you'll see that the task is marked as `UP-TO-DATE` the second time.

You need the latest snapshot to make this work. Use the following:

```gradle
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath 'de.undercouch:gradle-download-task:3.3.0-SNAPSHOT'
    }
}

apply plugin: 'de.undercouch.download'
```

I hope this helps. Stay tuned for the new version of gradle-download-task which will contain support for entity tags and which I hope to release soon.

Cheers,
Michel

**Comment by ssoloff** [comment]
Thanks, @michel-kraemer!

And there's no rush on delivering this feature.  Since opening this issue, I've discovered that the service hosting the file I need to download, while providing an `ETag` response header, does not currently honor the `If-None-Match` request header.  I have an open ticket with the service provider who confirmed that this was simply an oversight on their part. :smiley:

**Comment by michel-kraemer** [comment]
I just pushed a commit implementing this feature.

At the moment the plugin does not differentiate between weak and strong entity tags. I'm wondering if we should add an option to disable weak tags. What do you think?

**Comment by ssoloff** [comment]
> At the moment the plugin does not differentiate between weak and strong entity tags. I'm wondering if we should add an option to disable weak tags.

Sounds like a good idea.  However, from my perspective as an end user, I may just set `useETag` to `true` and not realize the service is returning a weak tag.  **Would it be possible for the task to display a warning if a weak tag is returned?**  That would at least trigger me to think about the implications and possibly use the proposed option to disable weak tags.

If such a warning were displayed, I don't know if you'd need yet _another_ option for users to suppress the warning in the event they know what they're doing with respect to weak tags.  Maybe a better alternative is to have a tri-state option for weak tags?  Let's assume it's called `allowWeakETags`, is of type `Boolean`, and has the following possible values:

* `null` (default): uses the weak ETag but displays a warning
* `true`: uses the weak ETag and does not display a warning
* `false`: ignores the weak ETag

Does that make sense?

**Comment by michel-kraemer** [comment]
How about extending the `useETag` flag as follows?

* `false`: Do not use ETags
* `true`: Use all ETags but display a warning for weak ones
* `"all"`: Use all ETags but do not display a warning for weak ones
* `"strongOnly"`: Use only strong ETags

**Comment by ssoloff** [comment]
:+1: That works for me!

**Comment by michel-kraemer** [comment]
Thanks. I implemented it this way. The feature will be in the next version.

**Comment by ssoloff** [comment]
Thanks for working on this feature, @michel-kraemer!
