### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by hdtuan87** [michel-kraemer/gradle-download-task#86]
error logs 
`Error:Circular dependency between the following tasks:
:moneyLover:downloadFile
\--- :moneyLover:downloadFile (*)
(*) - details omitted (listed previously)`

in gradle

     buildscript {

      repositories {
        maven { url 'https://maven.fabric.io/public' }
        jcenter()
      }

      dependencies {
        classpath 'io.fabric.tools:gradle:1+'
        classpath 'de.undercouch:gradle-download-task:3.2.0'
        }
      }

      apply plugin: 'de.undercouch.download'
      task downloadFile(type: Download) {
        src 'https://myhost/data/file.json'
        dest 'src/main/assets/'
      }

please help.

**Comment by michel-kraemer** [comment]
@hdtuan87 It's hard to read your build script, because the formatting broken. However, as far as I can tell, everything looks OK.

It seems you have multiple projects. Maybe the issue is in the parent project or in one of the other subprojects?

**Comment by hdtuan87** [comment]
@michel-kraemer Yes. I have multiple projects. The script above is from parent project, subprojects do not use plugins.

Do you have any ideas?

**Comment by michel-kraemer** [comment]
Please try to disable all subprojects and then enable one after the other. This way you should be able to find the project containing the offending code.

**Comment by hdtuan87** [comment]
I create new project.    
build.gradle

    apply plugin: 'com.android.application'

    buildscript {

        repositories {
            jcenter()
        }

        dependencies {
            classpath 'de.undercouch:gradle-download-task:3.2.0'
        }
    }

    android {
        compileSdkVersion 25
        buildToolsVersion "25.0.2"
        defaultConfig {
            applicationId "com.example.scorpion.testproject"
            minSdkVersion 15
            targetSdkVersion 25
            versionCode 1
            versionName "1.0"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }
    tasks.whenTaskAdded { task ->
        task.dependsOn downloadFile
    }

    apply plugin: 'de.undercouch.download'

    import de.undercouch.gradle.tasks.download.Download

    task downloadFile(type: Download) {
        src 'https://myhost/data/file.json'
        dest 'src/main/assets/'
    }

    dependencies {
        compile fileTree(include: ['*.jar'], dir: 'libs')
        androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
            exclude group: 'com.android.support', module: 'support-annotations'
        })
        compile 'com.android.support:appcompat-v7:25.3.1'
        compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'
        testCompile 'junit:junit:4.12'
        compile 'com.android.support:design:25.3.1'
     }

Error log:

    Error:Circular dependency between the following tasks:
    :app:downloadFile
    \--- :app:downloadFile (*)
    (*) - details omitted (listed previously)

You can send for me full gradle file can run task download?

**Comment by michel-kraemer** [comment]
I think the problem is this block:

```gradle
tasks.whenTaskAdded { task ->
    task.dependsOn downloadFile
}
```

This means you add the `downloadFile` task as a dependency to all tasks in your project - including `downloadFile` itself!

You should do something like this instead:

```gradle
tasks.whenTaskAdded { task ->
    if (task != downloadFile) {
        task.dependsOn downloadFile
    }
}
```

This should fix your problem.

Cheers,
Michel

**Comment by hdtuan87** [comment]
thank michel-kraemer
