### ISSUE TITLE
Conditional download based on checksum

### ISSUE THREAD

**Issue by ketan** [michel-kraemer/gradle-download-task#89]
I'm using this plugin to download a file from github releases, and the plugin will download a file everytime. I noticed a PR to check based on etag, but I feel that'll still make a network call to fetch the ETag.

What would be nice is to make the task idempotent and not download the file if the checksum matches.

Would you be OK to accept a PR to download and verify in a single action that makes the task idempotent:

```groovy
download {
  src ...
  dest ...
  checksum ...
  algorithm ... // optional
}
```

The above should avoid hitting the network if the checksum matches, if the checksum fails the file should be downloaded afresh and a checksum performed after the download completes successfully.

**Comment by michel-kraemer** [comment]
This sounds like an interesting idea, but I wonder how this feature would be different from just checking if the file already exists locally or not. How would the checksum ever not match if the file has been downloaded successfully previously? Can you please elaborate your use case? Thanks.

**Comment by vic-cw** [comment]
I think a caching mechanism through the ~/.gradle directory is always useful. Sure, one could do it manually, but I think it is typically an important feature of this plugin to enable it.

Or does it already do that ?

**Comment by vic-cw** [comment]
I have written a very quick workaround :

```
import de.undercouch.gradle.tasks.download.Download

def urlToCachePath(url) {
	def domainStart = url.indexOf("//")
	if (domainStart == -1)
		domainStart = 0
	else
		domainStart += 2
	def urlWithoutProtocol = url.substring(domainStart)
	def restStart = urlWithoutProtocol.indexOf("/")
	if (restStart == -1)
		restStart = urlWithoutProtocol.length 
	def domain = urlWithoutProtocol.substring(0, restStart)
	def queryStart = urlWithoutProtocol.indexOf('?')
	if (queryStart == -1)
		queryStart = urlWithoutProtocol.length()
	def rest = urlWithoutProtocol.substring(restStart, queryStart)
	return System.getProperty("user.home") + 
		"/.gradle/caches/modules-2/files-2.1/de.undercouch/cache/" + 
		domain.tokenize('.').reverse().join('/') + rest
}

def urlToCachedFile(url) {
	def fileStart = url.lastIndexOf("/") + 1
	def fileEnd = url.indexOf("?")
	if (fileEnd == -1)
		fileEnd = url.length()
	def file = url.substring(fileStart, fileEnd)
	return file
}

def createCacheTask(url) {
	task "cacheFile_${url.hashCode()}" (type: Download) {
	 	def destPath = urlToCachePath(url)  
	    src url
	    dest destPath
	    overwrite false
	}
}

def createDownloadTask(url, dest) {
	createCacheTask(url)
	task "download_${url.hashCode()}_${dest.hashCode()}" (type: Copy) {
		dependsOn "cacheFile_${url.hashCode()}"
	 	def destPath = urlToCachePath(url)
	 	from (destPath) {
	 		include urlToCachedFile(url)
	 	}
	 	into dest
	}
}
```

**Comment by michel-kraemer** [comment]
@vic-cw Thanks for the snippet. I'm not sure if this answers @ketan's question though. I'm waiting for feedback.

**Comment by ketan** [comment]
Thank you for getting in touch. I'm currently on vacation, I'll respond to this when I'm back next week.
