### ISSUE TITLE
Add FTP protocol support 

### ISSUE THREAD

**Issue by aleksey-zvolinsky** [michel-kraemer/gradle-download-task#92]
It will be great enhancement if we can download via FTP protocol also

**Comment by michel-kraemer** [comment]
Thanks for the idea. It's very interesting, but I think this would be a completely different plugin. This plugin has been designed for HTTP(S). If I wanted to support other protocols, I'd have to (a) add additional dependencies (i.e. libraries to connect to FTP servers, SFTP or the like) which I'd like to avoid, and (b) make sure all configurable properties still make sense. For example, `headers` or `useETag` do not make sense for FTP.

In addition, almost all properties would have to be implemented for each protocol, which would increase the maintenance overhead a lot.

I'm closing this issue for now. If there are other users who wish to have this feature, please vote for it by adding a GitHub reaction.
