### ISSUE TITLE
Version 3.3.0 not published correctly

### ISSUE THREAD

**Issue by mstefaniak10** [michel-kraemer/gradle-download-task#95]
When I try to load the latest version of the plugin using this code

plugins {
    id 'de.undercouch.download' version '3.3.0'
}

I get this error 

Error:Could not find de.undercouch:gradle-download-task:3.3.0.
Searched in the following locations:
    https://plugins.gradle.org/m2/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.pom
    https://plugins.gradle.org/m2/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.jar
Required by:
    project :

I believe it is due to this issue

https://discuss.gradle.org/t/plugin-authors-please-use-the-latest-plugin-publish-plugin-others-may-result-in-a-broken-upload/23573

**Comment by matklad** [comment]
Gentle ping @michel-kraemer :)

**Comment by michel-kraemer** [comment]
Thanks for reporting. This has been fixed in 57553fe5538a3a3a444662a96d611262fa327371. I just re-uploaded 3.3.0. Sorry for the inconvenience.
