### ISSUE TITLE
Download Directory causing Certificate issue

### ISSUE THREAD

**Issue by venh** [michel-kraemer/gradle-download-task#97]
I have a gradle file where I am using your plugin. I am able to download a file from artifactory. But, I had to pass the argument "acceptAnyCertificate" with a value true and also the credentials. Now, I am trying to download a directory. But I am getting a certificate error. The error is "sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.". However, I tried passing the argument "acceptAnyCertificate", but no luck. Can you please help?

**Comment by michel-kraemer** [comment]
Thanks for reporting the issue. Have you read the following StackOverflow thread?

https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

If the problem persists after following the steps, would it be possible to provide a URL to a publicly available file causing the problem, so I can reproduce it? Without being able to reproduce the issue, it will be very hard to fix it. Thanks.
