### ISSUE TITLE
OnlyIfModified should be true by default

### ISSUE THREAD

**Issue by dmitrij-drandarov** [michel-kraemer/gradle-download-task#98]

**Comment by michel-kraemer** [comment]
Can you please elaborate? Do you have a specific use case? I'm hesitant to change the default behaviour of such a central configuration item.

**Comment by dmitrij-drandarov** [comment]
The default behaviour caused my tasks to download a 80 MB ZIP-File everytime I ran the task.
I believe this is highly unintuitive and contrary to Gradles default Up-To-Date machanic.

It took me over an hour to figure out why this happened, because I was so accustomed to the default Up-To-Date check in Gradle. This may as well be my fault though for looking in the wrong places.

**Comment by michel-kraemer** [comment]
Ah OK. I see what you mean. However, as I said, the configuration item is very central and changing its default behaviour might break existing builds. I'm afraid we cannot do this for the time being (unless someone else has a good idea for a workaround).

**Comment by dmitrij-drandarov** [comment]
I can absolutely understand that. For now you could add a paragraph to *Usage* or *Examples* in the README to showcase the default behavior vs. what people might expect the default behaviour to be. 

Being down there in a long list of properties shouldn't be the only place to find such the "default behaviour of such a central configuration item". ;)

**Comment by michel-kraemer** [comment]
That's a good idea! Thanks. I amended the README accordingly.
